### ISSUE TITLE
Improve error message for failed commands

### ISSUE THREAD

**Issue by sabbyanandan** [spring-projects/spring-shell#103]
As a user, I'm trying to use the `http post` command and upon failures, I'm seeing very high-level error messages without any "caused by" or other details. 

**example:**

```
dataflow:>http post --file /home/gpadmin/labs/scdf-intro/dataFileEnriched.json
Command failed java.lang.reflect.UndeclaredThrowableException
```

The actual cause of the failure is that the file does not exist.

**Comment by prongs** [comment]
Yeah, this seems to be a problem when you throw an unchecked exception. One workaround for using file arguments would be to have the type of the argument as `File` instead of `String`.

**Comment by ericbottard** [comment]
Tidying old 1.x issues.

Shell 2 has builtin support for printing details of an exception after the fact
