### ISSUE TITLE
CommandAvailability is not documented

### ISSUE THREAD

**Issue by The4thLaw** [spring-projects/spring-shell#1053]
The documentation at https://docs.spring.io/spring-shell/reference/commands/availability.html explains how one can achieve dynamic command availability.

However, it seems that the documented annotation is only applicable on `@ShellMethod` commands, i.e. using the legacy annotations.

The new `@Command`-based methods should apparently use `@CommandAvailability` and rely on the `AvailabilityProvider` functional interface.

Perhaps the documentation should, also in this case, make a distinction between legacy and recommended annotations.

**Comment by jvalkeal** [comment]
You're right about this. That section indeed feels confusing and not clear.
