### ISSUE TITLE
Converter must allow conversion based on generic parameter types

### ISSUE THREAD

**Issue by hoomanv** [spring-projects/spring-shell#106]
org.springframework.shell.core.Converter should support conversion using the generic type of method parameters not just their basic raw type.
I have lots of methods that take generic arguments and I have absolutely no clue how to work around this deficiency. Rewriting SimpleParser from scratch is an option but overkill.

**Comment by hoomanv** [comment]
To be more specific, one of my method parameters is of type java.util.List<MyEnum>
I can use a json parser that can convert a string such as "['A','B']" to my desired type but only if spring-shell's Converter supplies me with the actual generic type of the argument.
Previously I had MyEnum[] as the parameter type and it used to work. Our new api requires me to have List and I'm desperate how to fix it.

**Comment by ericbottard** [comment]
As you may have noticed, Spring Shell uses its own Converter abstraction that is more limited than what you can find in Spring core. Unless we perform a full rewrite, that's the way it is, sadly.

I am a bit curious about your particular use case though. Are you writing a custom converter? You're saying "your API changed". Which API? Your JSON parsing API? Why can't you continue using a `MyEnum[]` signature and delegate to a `List<MyEnum>` call afterwards? Shading some lights on what you're trying to achieve and what exactly you have at hand may help find a solution.

**Comment by hoomanv** [comment]
> Why can't you continue using a MyEnum[] signature and delegate to a List<MyEnum> call afterwards?

This is a requirement imposed by the project I'm working on. We used to work with arrays but future versions require List and methods that took array no longer exist. We could keep those methods as deprecated but that's not our long term plan.

BTW I managed to work around it using my own InputConverter class which takes both a `Class<?> rawType` and a `Type type` argument in its methods. I had to replicate the entire SimpleParser code in order to switch Converter with InputConverter.

I can see possibilities to incorporate this fix into spring-shell without breaking the old Converter api.

```java
interface InputConverter {
   boolean supports(Class<?> rawType, Type type, String options);
   T convertFromText(String value, Class<?> rawType, Type type, String options);
   boolean getAllPossibleValues(List<Completion> completions, Class<?> rawType, Type type, String existingData, String options, MethodTarget target);
}
```

I can see possibilities to incorporate this fix into spring-shell with slight modifications.

**Comment by ericbottard** [comment]
I'm glad you managed to accomodate your API changes on your side. I will thus close this issue.

At the moment, we're not willing to disrupt the existing spring shell API any further, instead focusing efforts on performing a profound rewrite, which will leverage existing spring core APIs where applicable. Thanks for your much appreciated feedback.
