### ISSUE TITLE
StyleSettings interface "highlight" method failing to apply style.

### ISSUE THREAD

**Issue by pXius** [spring-projects/spring-shell#1063]
**Context:**
Overriding `org.springframework.shell.style.StyleSettings` allows you to change tag styling behaviour. Ie. You can override "style-title" to render "**_bold,italic_**" instead of just "**bold**".

The overridden `StyleSettings` can then be used as part of `ThemeSettings` to create a new Theme.

An example can be found [here](https://github.com/spring-projects/spring-shell/blob/main/spring-shell-samples/spring-shell-sample-catalog/src/main/java/org/springframework/shell/samples/catalog/CatalogConfiguration.java#L50) in the Catalog Sample App.

**Expected behaviour:**
All styling returned by overridden highlight() method should be applied.
```java
@Override
public String highlight() {
	return "bold,italic,fg:bright-cyan";
}
```

**Current Behaviour**
Only **bold** and _italic_ are applied, color and other styling options seem to be ignored.

This behaviour is also present in the Catalog sample app on branch `3.2.4`, `3.3.0-M1` and `main`.

Tested on various terminals on MacOs Sonoma 14.4.1 using ZSH.
Tested on default terminal on Ubuntu 22.04.4 LTS using Bash.

Here is the Catalog app where the highlighted row is expected to be `bright-cyan` as per code [here](https://github.com/spring-projects/spring-shell/blob/main/spring-shell-samples/spring-shell-sample-catalog/src/main/java/org/springframework/shell/samples/catalog/CatalogConfiguration.java#L50).  

![image](https://github.com/spring-projects/spring-shell/assets/64472458/1caad2c5-4fc0-45ba-9001-b670cac054cd)

**Comment by jvalkeal** [comment]
Thanks for detailed report and pointing this out as it's a silly oversight.

**Comment by jvalkeal** [comment]
@pXius It'd be great if you could check from main if I missed something.

**Comment by pXius** [comment]
@jvalkeal 
Works a treat!

Thank you very much for tackling the issue so fast.
