### ISSUE TITLE
Eclipse console: ANSI output problem

### ISSUE THREAD

**Issue by mojo2012** [spring-projects/spring-shell#109]
Hi guys,

I'm running my spring shell in eclipse's console window, but unfortunately it doesn't work correctly.
I get strange characters printed along my messages.

It looks like this:
![bildschirmfoto 2016-10-18 um 19 40 59](https://cloud.githubusercontent.com/assets/1330361/19489273/dc04db10-956a-11e6-87eb-c6237e1de5b7.png)

I debugged the problem and it seems that UnixTerminal is detecting that the Eclipse console is supporting ANSI colors, which is obviously not true.
So the colors are not interpreted and directly printed on screen

I hope you can fix this bug soon.

**Comment by ericbottard** [comment]
This is because your eclipse console mistakes the shell tty as an ansi capable tty, for some reason.

You can either
1) force the JLine terminal type to _e.g._ `off` (see https://github.com/jline/jline2/wiki/Terminal%20Factory%20Configuration)
2) use an eclipse plugin that adds an ANSI capable console (see _e.g._ https://marketplace.eclipse.org/content/ansi-escape-console)

**Comment by mojo2012** [comment]
But as I see it there are only two implementations, Windows and UnixTerminal. And in UnixTerminal the "isAnsiAvailable" flag is hardcoded set to true.

**Comment by ericbottard** [comment]
There is a third option (_e.g._ off):

>Available terminal types:

>* Unix (optional ANSI support)
>* Windows (optional ANSI support)
>* Unsupported

**Comment by mojo2012** [comment]
Ok, thanks. But is there no way to determine if it's running inside eclipse?

**Comment by ericbottard** [comment]
Normally, the terminal is correctly reported as far as I recall. For some reason, yours is not.
Please note that Spring Shell is really meant to be an interactive application, benefiting from colors, tab completion, etc. So while running inside eclipse is supported, it's not really a major target.

I shall close this issue if that's ok with you

**Comment by mojo2012** [comment]
Yes you can close it. I'm only running it inside eclipse during implementation because it's  easier

**Comment by ericbottard** [comment]
I understand. Thanks for your feedback
