### ISSUE TITLE
Incorrect documentation link for version 3.2.6

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-shell#1101]
On https://spring.io/projects/spring-shell#learn 3.2.6 links to https://docs.spring.io/spring-shell/reference/index.html, which shows the documentation for version 3.3.1.

**Comment by jvalkeal** [comment]
Yes thank pointing it out. It should link to https://docs.spring.io/spring-shell/reference/3.2/index.html so that used don't need to select it from a drop-down menu.

**Comment by jvalkeal** [comment]
This has been fixed.
