### ISSUE TITLE
Asciinema casts are not rendered in documentation

### ISSUE THREAD

**Issue by Klopfy** [spring-projects/spring-shell#1111]
Cross-referencing opened issue on https://github.com/spring-io/antora-ui-spring/issues/264 for visibility.

Asciinema casts are not being rendered in the documentation currently: [documentation](https://docs.spring.io/spring-shell/reference/tui/views/progress.html#_customisation) / [source code](https://github.com/spring-projects/spring-shell/blob/v3.3.1/spring-shell-docs/modules/ROOT/pages/tui/views/progress.adoc#customisation)

### Screenshot
<img width="864" alt="Screenshot 2024-08-03 at 11 23 02 PM" src="https://github.com/user-attachments/assets/d928007f-ad6d-4d63-adeb-27534483af8f">

**Comment by jvalkeal** [comment]
This is now fixed.

**Comment by Klopfy** [comment]
Thanks @jvalkeal, I confirm it is fixed for both spring documentation and my own one! Cheers
