### ISSUE TITLE
Inconsistent behaviour on passing invalid argument

### ISSUE THREAD

**Issue by kulkarnipradnyas** [spring-projects/spring-shell#1120]
```
@Command(command = "activate", group = "Activate/Deactivate Commands")
public class ActivationCommand {
    @Command(command = "test", description = "test")
    public void activateTest(
            @Option(longNames = "id", required = true, description = "test ID") Long id,
            @Option(longNames = "name", required = true, description = "test name") String name
            ){
        System.out.println("Activating test with id: " + id+ name);
    }
}
```
For the above code, I am getting the below inconsistent result. When an invalid argument is passed as a first argument then the shell throws an error log but when it is passed at the end it just ignores that.  It should throw an error log on both cases.

<img width="544" alt="Screenshot 2024-08-16 at 1 04 54 PM" src="https://github.com/user-attachments/assets/04303a35-2d25-46cf-80af-787a9e8269c9">
<img width="554" alt="Screenshot 2024-08-16 at 1 05 40 PM" src="https://github.com/user-attachments/assets/46a5a4ff-0fc0-484c-887d-7bf3916e1f17">

**Comment by jvalkeal** [comment]
Thanks for reporting. Looks like `--invalid` and `true` are passed to `name` option as an arguments in this case. That's clearly wrong.
