### ISSUE TITLE
Plain Help Command should not show unavailable Commands

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-shell#115]
`CommandMarker` methods that are **unavailable** (`@CliAvailabilityIndicator` returns `false`), should not **by default** listed using the plain help command. Instead, unavailable commands might be listed when **help** is supplied with an additional (optional) parameter e.g.:

```
help --all
help --all stream
```

Right now there is no visual indication, whether a command is available or not.

**Comment by ericbottard** [comment]
Tidying old 1.x issues.

Adding this feature to the backlog of Shell 2
