### ISSUE TITLE
Tweak the shell itself

### ISSUE THREAD

**Issue by anton-johansson** [spring-projects/spring-shell#121]
I'd like to make some modifications to the actual `Shell` implementation, but I can't really find a good way. What I did was creating a class, extending `JLineShellComponent` and I did my tweaks there. I annotated it with `@Component("shell")`, but it seems like `Bootstrap` adds its own instance, overriding mine, even if one already exists in the container.

Any ideas of what I can do?

**Comment by ericbottard** [comment]
These kind of customisations were not foreseen at the time. The best route is to use a custom equivalent of the `Bootstrap` class
