### ISSUE TITLE
About BannerProvider class getVersion () method。

### ISSUE THREAD

**Issue by wayss000** [spring-projects/spring-shell#125]
When BannerProvider class getVersion () method to return the string is too long, in the windows, the shell starts to show a problem。
![1](https://cloud.githubusercontent.com/assets/21314261/26296088/aafc5c70-3eff-11e7-8653-3d013d5b0017.png)
![2](https://cloud.githubusercontent.com/assets/21314261/26296090/aec90a38-3eff-11e7-8c08-31afc93dd89f.png)
I would like to know whether the version of the window does not show information, only show the shell name?

**Comment by ericbottard** [comment]
Hi, this seems to be a very specific issue when using non standard version numbers.
I'm afraid this behavior has no reason to be integrated by default in Spring Shell.

For your particular case, I recommend that you override the banner provider and use whatever logic is necessary to prevent your problem (for example, test whether the OS is Windows and your version number is longer than x characters, and truncate).

**Comment by wayss000** [comment]
Thank you very much.
My solution is similar to your suggestion, and I get the return value of getVersion () to be short, and the other display information is in the getBanner () method.
This is a limitation of windows cmd.
