### ISSUE TITLE
How to use log4j to manage spring-shell console ?

### ISSUE THREAD

**Issue by chilly** [spring-projects/spring-shell#126]
HandlerUtils  can not be extended.

六月 30, 2017 3:40:26 下午 org.springframework.shell.core.AbstractShell handleExecutionResult
信息: copy done

here. I want only output "copy done". How to do ? Only change spring-shell HandlerUtils code ?

**Comment by ericbottard** [comment]
Hi. You can directly output text using `System.out.println()` in your command if you wish

**Comment by chilly** [comment]
Yes. use System.out.println() to solve my problem. But Another problem: how to test.

**Comment by chilly** [comment]
Assert.assertEquals(cr.getResult(),"copy done");  
to listen system.out ?

**Comment by ericbottard** [comment]
As an alternative to System.out.println(), you can indeed have "copy done"
be the result of your command (it will be printed AND you can test that it
is the return value)

**Comment by chilly** [comment]
No, no, no.
mvn clean install 
java -jar target/xx.jar "cp --from ./src/test/resources/testLocal2Local --to /tmp/testLocal2Local2"
If I return String in my function. The console will print:

六月 30, 2017 3:40:26 下午 org.springframework.shell.core.AbstractShell handleExecutionResult
信息: copy done

If I change to System.out.println()  and not return String value. 
The testcase can not get any information from  CommandResult： 



        JLineShellComponent shell = bootstrap.getJLineShellComponent();

        CommandResult cr = shell.executeCommand("cp --from ./src/test/resources/testLocal2Local --to /tmp/testLocal2Local");
        
        Assert.assertTrue(cr.isSuccess());
        Assert.assertEquals(cr.getResult(),"copy done");

The only way to make both happy is: not use shell.executeCommand and CommandResult in testcase. Only test inner cmd function.

**Comment by ericbottard** [comment]
Are you saying that 
```
六月 30, 2017 3:40:26 下午 org.springframework.shell.core.AbstractShell handleExecutionResult
信息: 
```

is part of what is printed in the console when you run your command in the shell? This is not normal. Most likely you've messed with the logger configuration.

Have a look at what happens when I run the `date` command (which is a builtin command in Spring Shell):
```
 _____            _               _____ _          _ _
/  ___|          (_)             /  ___| |        | | |
\ `--. _ __  _ __ _ _ __   __ _  \ `--.| |__   ___| | |
 `--. \ '_ \| '__| | '_ \ / _` |  `--. \ '_ \ / _ \ | |
/\__/ / |_) | |  | | | | | (_| | /\__/ / | | |  __/ | |
\____/| .__/|_|  |_|_| |_|\__, | \____/|_| |_|\___|_|_|
      | |                  __/ |
      |_|                 |___/
1.2.1.BUILD-SNAPSHOT


Welcome to Spring Shell. For assistance press or type "hint" then hit ENTER.
spring-shell>date
Friday, June 30, 2017 11:39:55 AM CEST
spring-shell>
```

**Comment by ericbottard** [comment]
Hmmm, I see you run commands directly when invoking the shell (I assume this is what your `java -jar target/xx.jar` means.

**Comment by ericbottard** [comment]
This happens when running commands directly. Still, using the return value of your command is the right approach

**Comment by chilly** [comment]
So subclass of HandlerUtils can be injected is a good way ?

**Comment by ericbottard** [comment]
No I'd argue this is a bug in Spring Shell and those logs should not happen
in the first place

**Comment by MarcGiffing** [comment]
I've a long running process and I want to inform the user of the current process. How should I do this? I'm using Spring Shell 2. Sorry if its not the correct place here...

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
