### ISSUE TITLE
spring shell auto complete problem

### ISSUE THREAD

**Issue by chilly** [spring-projects/spring-shell#128]
I want create cmd like : cp   --from /abc/abc  --to /abc/abc
I write  my own Converter 
```
@Component
public class PathConverter implements Converter<String> {
   public boolean getAllPossibleValues(List<Completion> completions, Class<?> targetType, String existingData, String optionContext, MethodTarget target) {
// here my code
}
}
```

but when I run "java -jar cmd.jar"

I find "cp --f" will auto complete to => "cp --from"  
But when I type:
"cp --from /abc " => it call getAllPossibleValues(),  how to auto complete like
"cp --from /abc/abc" ?

**Comment by ericbottard** [comment]
Hi.

Take a look at [FileConverter](https://github.com/spring-projects/spring-shell/blob/master/src/main/java/org/springframework/shell/converters/FileConverter.java) which already does what you want, but for `java.io.File` as a source of inspiration (or just change your command argument type from `Path` to `File`)

**Comment by chilly** [comment]
Thanks. It is correct answer.
