### ISSUE TITLE
Provide additional info about connection problems

### ISSUE THREAD

**Issue by csterwa** [spring-projects/spring-shell#130]
Currently, when using Spring Cloud Data Flow shell and for some reason there is a connection issue to Data Flow server the shell doesn't always show sufficient information about what went wrong. For instance, here is a common result:

```
Welcome to the Spring Cloud Data Flow shell. For assistance hit TAB or type "help".
server-unknown:>
```

We did find that you can get some more information `dataflow config info` on the shell:

```
server-unknown:>dataflow config info
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowServerException: Unable to contact Data Flow Server at 'https://dataflow.****': 'org.springframework.web.client.HttpClientErrorException: 404 Not Found'.
```

It would be nice to get more specific information about what part of the connection had issues such as proxy, URL, credential or other configurations.

**Comment by ericbottard** [comment]
Moved to https://github.com/spring-cloud/spring-cloud-dataflow/issues/1625
