### ISSUE TITLE
Multiple values providers in single command?

### ISSUE THREAD

**Issue by jasonwjones** [spring-projects/spring-shell#143]
Is it possible to have multiple value providers (with multiple `@ShellOption`s in a single command?

I tried to set this up as follows:

```
public void printArtifact(@ShellOption(valueProvider = ArtifactIdValuesProvider.class) String artifact, , @ShellOption(valueProvider = PossibleArtifactTypeValuesProvider.class) String category) {
   ...
}
```

But the command completion only ever seems to trigger the values provider for the first shell option.

**Comment by ericbottard** [comment]
Hi Jason,

could it be that you suffered from a bug that prevented the first arg to be completed, and that I fixed [here](https://github.com/spring-projects/spring-shell/commit/6f79cc2686005993897d2d11a79addd6e2e6a000)

**Comment by ericbottard** [comment]
From a test I just ran (with the above commit applied), seems like there is an issue, but that would manifest the other way around at the moment: arguments that have already been set still get completion proposals. This is a know issue we're working on.

In any case, the expected behavior you describe in your report is indeed what should be supported, so be confident that this will be possible

**Comment by ericbottard** [comment]
Sorry, closed the wrong issue.
Still, could you confirm that the issue is gone when using the latest master (post efd9e24)?

**Comment by jasonwjones** [comment]
It looks like it's working as expected, I think we're all good. Thanks.

**Comment by jasonwjones** [comment]
On a bit of a sidenote, however, does the command completion keep reinstantiating the values providers over and over again? I'm trying to figure out why I'm getting a noticeable delay on things. For example, I now have two values providers on a command. The first one makes a web request to get the possible completion values, and the second is just a static list. Then I go to type my command use tab completion on the first parameter/argument and notice a small delay (since it's fetching values from a database). But then when I go to use tab completion for the second parameter, it still seems that I'm getting a bit of a delay, even though the second one is just hard-coded and should be pretty quick.

**Comment by ericbottard** [comment]
`ValueProviders` are spring beans, so are instantiated at ApplicationContext creation time.

Please make sure the first value provider is not being queried (by eg attaching a debugger, writing to console, etc) for the second value. I assume you extended `ValueProviderSupport` and hence benefit from its `supports()` implementation.

Please open another issue if there is indeed a problem with the framework
