### ISSUE TITLE
Completion issue when invoked just after multi word command

### ISSUE THREAD

**Issue by ericbottard** [spring-projects/spring-shell#150]
This fails: `register module<TAB>` (not the absence of space after `module`).
Will currently yield `register register module`

**Comment by markpollack** [comment]
The behavior observed is different than this the previous shell and makes the tab completion not usable.   In SCDF if I type `:>dataflow con<TAB>` it expands to `:> dataflow config ` with a space after config.  In the new shell, I hit tab after typing "con" I get the hint for available commands, then hitting tab again gives duplicate text, `:>skipper skipper config info` and <TAB> now cycles between the other two options, 'info' and 'server'.

It should not be allowed that a user can <TAB> their way to creating an incorrect input  Is there a workaround if this is indeed a JLine issue?

**Comment by ericbottard** [comment]
I think we can do something about it if we strip the prefix that's already in the buffer (JLine 3 takes care of that for us normally, but is being fooled in this case by the fact that there is a space).

Need to make a special case for commands (as opposed to args) though, as we don't want to quote.

I have an idea I can explore
