### ISSUE TITLE
Move already-set-params check to Shell for Completion

### ISSUE THREAD

**Issue by ericbottard** [spring-projects/spring-shell#152]
When invoking completion for `command(String arg1, int arg2)` using buffer `command --arg1 foo <TAB>`, there is no need to query completions of `arg1`, because it has already been set.

Currently, the `StandardParameterResolver` performs this check itself, while the simplified `LegacyParameterResolver` skips it.
This check can be pulled up at the core Shell level and benefit all resolvers.

**Comment by jvalkeal** [comment]
Not valid for 2.x/3.x, closing.
