### ISSUE TITLE
Expose an `Object evaluate(Input)` method at Shell level

### ISSUE THREAD

**Issue by ericbottard** [spring-projects/spring-shell#154]
The current implementation is `void evaluate(Input)` and applying the `ResultHandler` is part of the method implementation.
In all but one cases, `ResultHandler` is used to display result in some form.

The request to exit the shell should be handled separately, and a method that exposes the object result of invocation should be made public. This is to allow easier integration testing of the shell (provided there is a parser that can turn a String into `Input`)

**Comment by erki** [comment]
Why has the `Object evaluate(Input)` method been made `private` in **3.0.0-M3**? 

Currently, I'm using this method to evaluate a single command received via a websocket connection and pass the output back onto the same connection like it has been described here:

https://stackoverflow.com/questions/57135669/is-there-a-way-to-get-a-two-way-connection-from-client-browser-to-server-applica

If it is not possible to keep the evaluate method public, is there another (better) way to use a websocket as the underlying IO layer for spring shell?
