### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Vity01** [spring-projects/spring-shell#155]
I randomly checked this project if it is still alive and I am happy that you decided to rewrite the project from scratch. 
I will bring my ideas and suggestions later this week. I use it heavily for my project https://github.com/avast/hdfs-shell
I had to create my fork of SS because of some issues... 

..now you can close the issue... :-)

**Comment by ericbottard** [comment]
Hi,

always good to get feedback and knowledge of which users/projects leverage our technologies. Glad this is useful ;)
