### ISSUE TITLE
How to interact with the user during long running process

### ISSUE THREAD

**Issue by ericbottard** [spring-projects/spring-shell#158]
Ping @MarcGiffing

From https://github.com/spring-projects/spring-shell/issues/126#issuecomment-330272492

> I've a long running process and I want to inform the user of the current process. How should I do this? I'm using Spring Shell 2. Sorry if its not the correct place here...

You should interact with `System.out` or the JLine `Terminal` directly for that, using your logging framework of choice only to log to something else (eg a File) so that it does not pollute the screen

**Comment by MarcGiffing** [comment]
Thanks for the response but I can't inject the Terminal bean to use it. Its lazy initialized after all other beans.

I've created a Configuration class which injects the Jline Terminal but I got a dependency cycle error. I've also tried to auto configure it after the SpringShellAutoConfiguration (@AutoConfigureAfter(SpringShellAutoConfiguration.class)) but without luck.


`
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   terminalConfiguration (field private org.jline.terminal.Terminal com.example.demo.TerminalConfiguration.terminal)
      ↓
   org.springframework.shell.jline.JLineShellAutoConfiguration (field private org.springframework.shell.Shell org.springframework.shell.jline.JLineShellAutoConfiguration.shell)
┌─────┐
|  shell defined in class path resource [org/springframework/shell/SpringShellAutoConfiguration.class]
↑     ↓
|  resultHandlerConfig
↑     ↓
|  mainResultHandler
↑     ↓
|  parameterValidationExceptionResultHandler (field private java.util.List org.springframework.shell.result.ParameterValidationExceptionResultHandler.parameterResolvers)
↑     ↓
|  standardParameterResolver
↑     ↓
|  commandValueProvider defined in class path resource [org/springframework/shell/standard/StandardAPIAutoConfiguration.class]
`

**Comment by ericbottard** [comment]
Yes, this is normal. Try putting `@Lazy` on your `Terminal` injection point
