### ISSUE TITLE
How to solve the problem of Chinese garbled display?

### ISSUE THREAD

**Issue by VerRan** [spring-projects/spring-shell#162]
when i dispaly Chinese in the class use @ShellComponent , the word display is messy code，how can i solve it，thanks!

**Comment by ericbottard** [comment]
Hi,

what's your OS? What's the terminal application you're using?
Can you use chinese characters in another application running in that terminal just fine?

**Comment by ericbottard** [comment]
Do you have any input to add here, otherwise I am going to close this issue.
I verified that I can output non trivial, UTF-8 characters when using iTerm on the mac. I don't have access to other environments, so without additional context, won't be able to help much
