### ISSUE TITLE
Support using Spring Boot without autoconfiguration enabled

### ISSUE THREAD

**Issue by shabino** [spring-projects/spring-shell#166]
I don't use autoconfiguration and therefore must manually \@Import the Spring Shell *AutoConfiguration classes myself.  However, because JLineShellAutoConfiguration isn't public, I can't do that.  As a workaround, I copied the code from this class and a couple of supporting classes  (also non-public) into my own project.

**Comment by ericbottard** [comment]
Fixed, see https://github.com/spring-projects/spring-shell/blob/c86b813fed6e1348cc5f2ef7c8c8e01745679d12/spring-shell-samples/src/main/java/org/springframework/shell/samples/noautoconf/NoAutoConf.java for a full example of what you'd need to import
