### ISSUE TITLE
Support for enums

### ISSUE THREAD

**Issue by vguna** [spring-projects/spring-shell#169]
I'm trying to use enums as `@ShellOption` to limit a parameter to a fixed list of possible values. It basically works but violating the conversion rules (e.g. not uppercase, not in enum values) prints an ugly `IllegalArgumentException` to the console - which is quite technical. Are there any plans to promote enums to first class citizens providing relaxed conversion and user-friendly error messages? Or is there some other option to provide some fixed strings the user can "select" from?

**Comment by ericbottard** [comment]
Allowing relaxed binding could be achieved by implementing both a converter and a `ValueProvider` (for completion). I'm not in favor of it, especially as the default behavior, but if you have strong interest in this (and/or a pull request), this could be considered.

For "other strings", this is basically the same story, but would need to be done in an _ad hoc_ fashion for your particular enums, so can't make it in Spring Shell proper.

**Comment by ericbottard** [comment]
Closing for now, please reopen if you think more context can be added
