### ISSUE TITLE
Missing Qualifier for ConversionService Bean

### ISSUE THREAD

**Issue by purnhar** [spring-projects/spring-shell#173]
The StandardAPIAutoConfiguration requires a bean of class ConversionService to create a ParameterResolver. In my ApplicationContext multiple ConversionService-Beans are available, which leads to the following error during startup:

```
Parameter 0 of method standardParameterResolver in org.springframework.shell.standard.StandardAPIAutoConfiguration required a single bean, but 2 were found:
	- mvcConversionService: defined by method 'mvcConversionService' in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
	- integrationConversionService: defined in null
```

The error occurs after just adding several spring-starter dependencies in a newly generated spring-boot pom. I boiled down the error to the following dependencies (web, integration and shell):

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-integration</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.shell</groupId>
			<artifactId>spring-shell-starter</artifactId>
			<version>2.0.0.M2</version>
		</dependency>

```

Im using spring-boot 2.0.0.M5 and spring-shell 2.0.0.M2. The error can also be reproduced with the current BUILD-SNAPSHOT.

**Comment by ericbottard** [comment]
Fixed via the commit referenced above. Please re-open this issue if it does not fox your issue
