### ISSUE TITLE
Support @ShellMethodAvailability on class?

### ISSUE THREAD

**Issue by jasonwjones** [spring-projects/spring-shell#175]
I've grouped many of my commands into several logical classes. I'm making use of `@ShellMethodAvailability` on various commands in order to enable/disabled based on connection to a data source. As it turns out, many of the classes of commands are written such that every single command is unavailable if there is no connection. If possible, it would be nice to be able to use `@ShellMethodAvailability` on the entire class and not have to put it on every method.

**Comment by ericbottard** [comment]
This is already supported by using `"*"` as the value of the `@ShellMethodAvailability` attribute and using that annotation on the _availability_ method (**not** the command method).

See the info section in the third case [here](https://docs.spring.io/spring-shell/docs/2.0.0.M2/reference/htmlsingle/#dynamic-command-availability):

> The default value for the @ShellMethodAvailability.value() attribute is "*" and this serves as a special wildcard that matches all command names. It’s thus easy to turn all commands of a single class on or off with a single availability method.

HTH, let me know if you think this is not obvious enough

**Comment by jasonwjones** [comment]
Sure enough, that works exactly as you said it would. In hindsight it is fairly obvious. I think I was just so stuck on the idea that it'd be a class-level annotation. Since I have several groups of commands I'm just going to inherit from a new class that supplies my availability method by default. As a small matter, it probably wouldn't be bad to have an additional example in the docs with this 'technique', to complement the current info box that talks about it briefly. Thanks!
