### ISSUE TITLE
Have ThrowableResultHandler use getMessage() instead of toString() on Throwable?

### ISSUE THREAD

**Issue by jasonwjones** [spring-projects/spring-shell#176]
If a command is currently unavailable, I might get the following output:

```
dshell[]:>list-artifacts
org.springframework.shell.CommandNotCurrentlyAvailable: Command 'list-artifacts' exists but is not currently available because you are not connected to a tenant
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
dshell[]:>
```

However, it seems that it might be better to actually use `getMessage()` instead of relying on `toString()`. The `toString()` method by default will append the class name, a colon, and the message. But this results in a bit of a terse message, which I can get anyway through a `stacktrace` command. This seems like better output (in this case):

```
dshell[]:>list-artifacts
Command 'list-artifacts' exists but is not currently available because you are not connected to a tenant
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
dshell[]:>
```

Yes, I can override `toString()` in the throwable (technically) but I don't think this would be the best approach. 

As an aside, the [current documentation](https://docs.spring.io/spring-shell/docs/current-SNAPSHOT/reference/htmlsingle/#dynamic-command-availability) seems to suggest that the class name isn't printed (i.e., `getMessage()` is being used:

```
shell:>download
Command 'download' exists but is not currently available because you are not connected.
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
```

**Comment by ericbottard** [comment]
Better indeed, fixed!
