### ISSUE TITLE
EventListener wont catch Application events when spring-shell is used

### ISSUE THREAD

**Issue by UncleInf** [spring-projects/spring-shell#177]
When using spring-shell and trying to catch event `@EventListener(ApplicationReadyEvent.class)` nothing happens. When  spring-shell is not used in the project it works appropriately. 

Tested with `spring boot 1.5.8`, `spring shell 2.0.0.M2`, `java 8`, `maven` with project generated from [start.spring.io](start.spring.io)

Are these info messages relative to the problem?
```
Bean 'org.springframework.shell.SpringShellAutoConfiguration' of type [org.springframework.shell.SpringShellAutoConfiguration$$EnhancerBySpringCGLIB$$7bc52fc5] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
Bean 'conversionService' of type [org.springframework.core.convert.support.DefaultConversionService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

**Comment by ericbottard** [comment]
No these warnings are unrelated.

`ApplicationReadyEvent` is fired _very_ late in the app lifecycle, and an app using Spring Shell never reaches that state (Spring Shell uses an `ApplicationRunner`, which enters an infinite REPL loop).

The `ApplicationRunner` Spring Shell uses (and any other(s)) are triggered by [this line](https://github.com/spring-projects/spring-boot/blob/723222aa952ddec294ccbcfbf4c54cfddd464d48/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L328) while the event you're hoping to catch is triggered by the line just [below](https://github.com/spring-projects/spring-boot/blob/723222aa952ddec294ccbcfbf4c54cfddd464d48/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L329).

I would suggest you listen for `ApplicationPreparedEvent` instead, if this is possible.
