### ISSUE TITLE
Document how to generate help usage instructions on Shell application startup

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-shell#178]
It is often a requirement for shell applications to provide a help flag when starting the application, e.g. `-?`, `-h`, `--help`. When providing such a flag user may want to print out a list of available command-line arguments and a short description.

In the most simple way this could be just a help-text file in the class-path (similar to the banner) that gets read and printed.

Optionally, there should be the ability to verify provided arguments and raise an issue if an invalid command line argument was provided.

This does not seem to be documented on how to implement this the recommended way using Spring Shell `2.0`

**Comment by ericbottard** [comment]
Command line args at the whole program level are not really handled by Spring Shell (although Shell provides a default behavior documented here https://docs.spring.io/spring-shell/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#_customizing_command_line_options_behavior), but rather a whole-application issue (typically taken care of by boot @ConfigurationProperties support, etc)

So My recommendation for your case would be to handle args using an `@Ordered` `ApplicationRunner` (including looking at `--help` to print your usage)
