### ISSUE TITLE
Feature Request: Translateable commands

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-shell#179]
Hi,
it would be great, if the shell could be customized to support other languages / translations for built-in commands and messages.
The default Spring MessageSource approach would work great.

Now, if I want to create a Shell application for a different language, I'd not only have to implement the Help command to translate it, but also other messages would still appear in English.

Best regards
Stefan

**Comment by jcamilorada-EBI** [comment]
@ericbottard are you accepting contributions? this one looks really interesting and I have been using spring shell , I really like it and  I would like to help. (I will recommend to you flag issues as  "ideal for contribution")

**Comment by Jcamilorada** [comment]
@ericbottard are you accepting contributions? this one looks really interesting and I have been using spring shell , I really like it and I would like to help. (I will recommend to you flag issues as "ideal for contribution")

**Comment by ssimd** [comment]
Glad to hear that this sounds interesting to more people than just me!

@Jcamilorada if you would like to implement this that would be great!

I imagined something like this:
* Spring Shell uses MessageSource to get/format the command messages to be printed
* All existing messages go to the default English message resource, which is bundled with Spring Shell
* If desired, there can be supplied one or more localized message resources that are loaded instead by Spring Shell
 * probably we could use the Locale settings?

About the last part, I am currently not fully sure how Spring generally handles it, but I think that would be the first place to look and then we would know how to do it in an optional "opt-in", non-intrusive way...

**Comment by jvalkeal** [comment]
Superseded by #668
