### ISSUE TITLE
Shell availability in Tomcat

### ISSUE THREAD

**Issue by arnonuem** [spring-projects/spring-shell#181]
Hi all,

how would i access the shell when my application is deployed in an external tomcat in a classic way?

**Comment by ericbottard** [comment]
This project is about an interactive shell that runs in a terminal, not a remote shell that can be accessed eg via telnet. Maybe you're confusing it with an embedded CRaSH shell? See https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-remote-shell.html
