### ISSUE TITLE
Allow customisation of Shell in auto-config

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-shell#182]
In case user wants to tweak created `Shell` and provide own version, `SpringShellAutoConfiguration` should simply use `@ConditionalOnMissingBean(Shell.class)` for `shell` bean.

**Comment by ericbottard** [comment]
This is not meant to be customized, unless there is a good usecase that needs to be supported. Spring Shell without this class is like SpringMVC without DispatcherServlet, it's not Spring Shell anymore
