### ISSUE TITLE
Rename main @Qualifier

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-shell#184]
Having
```
	@Bean
	@Qualifier("main")
	public ResultHandler<?> mainResultHandler() {
		return new TypeHierarchyResultHandler();
	}
```
I think `main` is a little too common name to be used in autowiring. Maybe just create `mainResultHandler` as a global static variable and then use that.

**Comment by ericbottard** [comment]
As discussed, I don't think this is a concern for the end user, and not part of the API. This is an implementation detail that is as good as any other. May be changed to `@Primary`
