### ISSUE TITLE
Support multiple same parameters

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-shell#186]
It'd be nice if you could do `mycommand --property foo1=bar1 --property foo2=bar2` and then use
```
@ShellOption(defaultValue = NULL) List<String> properties
```
Now we need to use single property and go crazy with delimiting that with comma which then complicates things.

**Comment by ericbottard** [comment]
Supported via https://docs.spring.io/spring-shell/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#_parameter_arity (assuming the size of the list is known in advance. Infinite arity is coming in a next version)
