### ISSUE TITLE
Allow to use dynamic commands

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-shell#188]
Lets assume we have an `upgrade` command with set of update strategies. Every strategy has its own dedicated set of properties. With current shell we could do:
```
upgrade
   --release-name mylog --package-name log --package-version 2.0.0
   --upgrade-strategy bluegreen
   --strategy-properties “timeout=1,interval=1”

upgrade
   --release-name mylog --package-name log --package-version 2.0.0
   --upgrade-strategy rolling
   --strategy-properties “timeout=1,interval=1,rollout=0,unavailable=0”
```

It'd be nice if we could dynamically resolve more fine grained commands having customised options:

```
upgrade bluegreen
   --release-name mylog --package-name log --package-version 2.0.0
   --strategy-property-timeout 1
   --strategy-property-interval 1

upgrade canary
   --release-name mylog --package-name log --package-version 2.0.0
   --strategy-property-timeout 1
   --strategy-property-interval 1
   --strategy-property-rollout 0
   --strategy-property-unavailable 0
```
This would allow users to know exactly what options are available without needing to know these at compile time.

**Comment by ericbottard** [comment]
This is already possible having two distinct commands whose keys are `upgrade bluegreen` and `upgrade canaray` respectively. They can be dynamically enabled/disabled according to https://docs.spring.io/spring-shell/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#dynamic-command-availability.
The only thing that is not possible (and won't be anytime soon) is to discover new commands in a completely dynamic manner (eg communicating with a remote server). Commands are java annotated methods, that's one of the foundations of Spring Shell (in its current form at least)
