### ISSUE TITLE
Dynamic disable Spring Shell

### ISSUE THREAD

**Issue by michalgce** [spring-projects/spring-shell#190]
Hey there, i would like to use spring-shell only in case of using "developer" @Profile, is there any way right now to disable it dynamically?

**Comment by michalgce** [comment]
Right now i'm using following solution
```java
@Component
@Profile("!developer")
public class CliAppRunner implements ApplicationRunner {
    public CliAppRunner() {

    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        //do nothing
    }


}
```

**Comment by ericbottard** [comment]
This is a solution indeed, I guess.I'm curious though about your use case. What should happen when you're not using the `developer` profile? What should the application do?

**Comment by iman-zolfaghari** [comment]
You could also disable the shell with below property in the application.properties:
spring.shell.interactive.enabled=false

**Comment by jvalkeal** [comment]
Closing in favour of #377

**Comment by tsayao** [comment]
I did:

```
@EnableAutoConfiguration(exclude = {SpringShellAutoConfiguration.class,
                                    JLineShellAutoConfiguration.class,
                                    StandardAPIAutoConfiguration.class,
                                    StandardCommandsAutoConfiguration.class})
```

The use case is that's an end user app which I might connect thru SSH and run "app --adm", so now I can do command line transactions.

**Comment by jardelnovaes** [comment]
For spring-boot 2.7+ and spring-shell 2.1+ it must be:

```java
@EnableAutoConfiguration(exclude = {
        SpringShellAutoConfiguration.class,
        JLineShellAutoConfiguration.class,
        StandardAPIAutoConfiguration.class,
        StandardCommandsAutoConfiguration.class,
        LineReaderAutoConfiguration.class,
        ShellRunnerAutoConfiguration.class
})
```
