### ISSUE TITLE
When to AutoConfigure the Shell?

### ISSUE THREAD

**Issue by sparcs360** [spring-projects/spring-shell#192]
I have an executable .jar containing my Shell Application.  This App has a dependency on two .jars that each define a set of Beans (some `@ShellComponent` commands and a `PromptProvider`).  Only one set of beans are conditionally loaded at runtime (via the `@Profile` mechanism).

I also have a Spring Booted REST Server that depends on the shared .jars... the Beans it uses are also conditionally loaded based on the active Profile.

![](https://www.planttext.com/plantuml/svg/SoWkIImgAStDuUAA3iv8pSbHS2meoCbCJYp9pC-BLKWiLYW6YN951xa6XoW4fnQLfHP1XC5ChcWjBP_CfAB4eae5PKCjBR1KJcQI8Og44KB2Y8iBRA22hguTH27482G-ihGHcZHGkqDgNWh8lG00)

**Problem**: When I start the REST Server, it also starts a Shell (which I don't want).  The reason is that the shared libraries require `spring-shell-core` (for the `PromptProvider`), but that module also contains `JLineShellAutoConfiguration` which starts up a `DefaultShellApplicationRunner` (because an `ApplicationRunner` bean isn't defined).

I can obviously workaround this, but wondered if there was any merit in moving the two auto-configuration classes (`SpringShellAutoConfiguration` being the other) out of `spring-shell-core` and into a separate `spring-shell-autoconfig` module?  This would allow me to "opt-out" of auto-configuration in the shared libraries.  Obviously, `spring-shell-starter` would include auto-config so we keep the default "opt-in" behaviour.

BTW, I'm liking the direction you've taken v2 in... good job!

**Comment by ericbottard** [comment]
Hi Lee,

I understand your issue. However, I'm not sure I'm ready to extract the autoconfigurations to suit your needs, for several reasons:
- one could argue it's *your* library1 and library2 that should be split and the shell parts be included by the shell application only.
- if we were to extract the AutoConfiguration classes to some extra jar, I'm worried we'll run into problems with JDK9 modules in the long run and would force us to make more classes/packages public than necessary

As a lucky coincidence though, https://github.com/spring-projects/spring-shell/pull/189 may provide you with a more elegant way to disable the *runners* (other autoconf would still kick in, which may not be desired).

Another approach, if you're not ready to split your 2 libs, is to make them depend on spring-shell marked as `<optional>true</optional>` and to re-depend on spring-shell in your shell-application.

Hope that helps.

I'm closing this ticket now, feel free to re-open if you think the answer is not satisfactory
