### ISSUE TITLE
On windows system, The tabular format generated by the API is in a mess.

### ISSUE THREAD

**Issue by wanghuizuo** [spring-projects/spring-shell#193]
system:：win10
spring-shell：2.0.0.M2

![image](https://user-images.githubusercontent.com/12987264/34968141-82fec032-faa2-11e7-907c-5497f1290b43.png)

**Comment by ericbottard** [comment]
What program terminal are you using? Can you confirm the padding characters are indeed space characters? Can you check the font and fixed-width setting you're using?

There is no particular reason why this would generate something different on windows, so must be a rendering setting

**Comment by wanghuizuo** [comment]
I run the `TableCommands` samples, running on different systems on different style, is this normal?

WIN7
![image](https://user-images.githubusercontent.com/12987264/34987524-6d1b1b0e-faf6-11e7-9946-d859757b27dd.png)

LINUX
![image](https://user-images.githubusercontent.com/12987264/34987497-557ecf36-faf6-11e7-831c-4da0958c8536.png)

**Comment by ericbottard** [comment]
Again, I believe this is a problem with the actual terminal program you're using. In the first case for example, what's the buffer line width?

**Comment by wanghuizuo** [comment]
Thank you for reminding me, this is my config.

![image](https://user-images.githubusercontent.com/12987264/34995692-3258cd56-fb12-11e7-8111-66b191296f34.png)

![image](https://user-images.githubusercontent.com/12987264/34995824-a648ff2e-fb12-11e7-8726-7dec7d95fcf7.png)

![image](https://user-images.githubusercontent.com/12987264/34995855-b70074b4-fb12-11e7-9d4f-5cb1f9bfce61.png)

**Comment by jvalkeal** [comment]
Closing this as in `2.1.x` win support will be much better due to jline and its deps.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
