### ISSUE TITLE
Shortcut Ctrl-C does not closes the application

### ISSUE THREAD

**Issue by obiasutti** [spring-projects/spring-shell#195]
Hello guys,

in the new released version 2.0.0 as well as in the 2.0.1 snapshot neither the quit/exit command, nor the Ctrl+c shortcut closes the application.

Let me know if you need more details on how to reproduce it, but it is pretty straightforward.

Cheer,
Otávio

**Comment by ericbottard** [comment]
Ouch.
I'm indeed seeing that CTRL-C doesn't exit anymore (it intercepts the ExitRequest that gets printed) but I'm able to quit by entering either `exit` or `quit`.

Can you confirm? I'm worried you'd have a different behavior, akin to something that has been previously reported and that I could not reproduce.

I'm using the sample application as my testcase:
```
java -jar spring-shell-samples/target/spring-shell-samples-2.0.0.BUILD-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.8.RELEASE)

my-shell:>exit

```
==> OK

But
```
java -jar spring-shell-samples/target/spring-shell-samples-2.0.0.BUILD-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.8.RELEASE)

my-shell:>CTRL-C
org.springframework.shell.ExitRequest
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
my-shell:>CTRL-C
org.springframework.shell.ExitRequest
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.

**Comment by obiasutti** [comment]
Thank you for the quick response @ericbottard! The CTRL-C illustration matches exactly the problem I have. However the quit/exit command still does not work. The application just hang, keyboard stops responding and I'm forced to close the console window.

I'm using Spring-Boot 1.5.9, but I just tried it with the 1.5.8 and got the same problem. I'll need more time to analyse what is causing it.

Thanks again!

Cheer,
Otávio

**Comment by obiasutti** [comment]
Hi @ericbottard, I just found out that I had running threads on the background that needed a bit longer to finish execution. It means the console eventually closes by itself on exit/quit.

Cheer,
Otávio

**Comment by Vity01** [comment]
Ctrl+C to exit the app is usually used on Windows. For bash-like applications the Ctrl+C should clear the prompt not to exit the app. Both ways should be supported.

**Comment by ericbottard** [comment]
So, there was a bug introduced (and fixed) recently.

But, ignoring that bug, the behavior is as follows:
- if the buffer is non-empty, CTRL-C clears the line
- if it is empty, it kills the app.

This behavior is on par with several other applications

**Comment by Vity01** [comment]
@ericbottard which applications? eg. when I use putty Ctrl+C always gives a new prompt

**Comment by T3rm1** [comment]
Yeah it doesnt make sense to exit the shell with ctrl+c. It should either clear the line or, when during a long running action, it should set a interrupted flag so the user can cancel the action.

**Comment by murat-tech** [comment]
2024 Still relevant issue - 
OS Mac 14.1.2
Java 21 
Spring Boot 3.2.4
