### ISSUE TITLE
Spring Context IT stopped running with 2.0.0.RELEASE

### ISSUE THREAD

**Issue by C-Otto** [spring-projects/spring-shell#199]
I have a simple test that just starts the application context. This worked fine with 2.0.0.M2, but it stopped working with 2.0.0.RELEASE. Now the test freezes with

2018-01-22 21:37:14.780  INFO 12988 --- [           main] xxx.XXXApplicationIT   : Started XXXApplicationIT in 3.694 seconds (JVM running for 7.74)

Java 9 and Java 8, Spring Boot 2.0.0.M7

I had to add the following configuration to make the test run (with M2):

```
@TestConfiguration
public static class TestApplicationRunner implements ApplicationRunner {
    @Override
    public void run(ApplicationArguments args) {
    }
}
```

**Comment by ericbottard** [comment]
Please review the changes in https://github.com/spring-projects/spring-shell/commit/f90edd42c41c738ed628805922c850c9b05c6730. This is likely due to the changes to the ApplicationRunners

**Comment by C-Otto** [comment]
I had to set `spring.shell.interactive.enabled=false` in my tests.
