### ISSUE TITLE
BorderStyle should be a normal class instead of a enum to allow users to define their own custom borders

### ISSUE THREAD

**Issue by isen-ng** [spring-projects/spring-shell#201]
BorderStyle is now an enum and there seems like there is no way to define custom styles and corners.

Make BorderStyle a normal class, and make Corners another class that is the input to the constructor to BorderStyle instead of the copy pasta `registerCorners`.

```
  public class CornerStyle {
    private static final CornerStyle OLD_SCHOOL = new Corner('+', '+', '+', '+', '+', '+', '+', '+');

    private char topLeft;
    private char topRight;
    private char bottomLeft;
    private char bottomRight;
    private char middle;
    private char left;
    private char right;
    private char bottom;

    .... 
  }

  public class BorderStyle {
    private static final BorderStyle OLD_SCHOOL = new BorderStyle('-', '|', CornerStyle.OLD_SCHOOL);
    private static final BorderStyle OLD_SCHOOL_THICK = new BorderStyle('=', '|', CornerStyle.OLD_SCHOOL);

    private char vertical;
    private char horizontal;
    private CornerStyle corners;

    ....
  }
```

**Comment by ericbottard** [comment]
PRs are very welcome.
One area where full extensibility could be problematic is where different styles meet (ie a double border crossing an old style border in a T shape pointing up => what should we print). Opening the system completely can't predict all combinations, even if user1 adds his style to the core set and takes care of all combinations, then if user2 comes in (and takes care of user2<=>core) there is still a potential gap in the user1<=>user2 case.

One could argue that such a case won't happen in practice, and that border styles won't be added in such a "plugin" dynamic way. Hence you as a user control everything. If you have a working PR, I'd be happy to merge it in.

**Comment by jvalkeal** [comment]
Closing if favour of #483 and tracking related work there.
