### ISSUE TITLE
Is it somehow possible to use AnsiColor with org.springframework.shell.table.Table

### ISSUE THREAD

**Issue by dmarthaler** [spring-projects/spring-shell#202]
When using the Table of Spring Shell, is it possible to use 
`AnsiOutput.toString(AnsiColor.RED, value)` for further formatting of values within cells?

I tried with a custom `org.springframework.shell.table.Formatter` implementation, but this only prints `[31m2`.

**Comment by ericbottard** [comment]
Sadly this is not currently not supported, as it is a non trivial task: not only do we want to avoid coupling the `table` sub-package to the rest of spring shell and JLine Ansi, but this would require careful handling when values are reformated (for example a single red String getting split to span 3 lines, etc).

This may be added in future versions, but pull requests are very welcome if you implement this yourself

**Comment by jvalkeal** [comment]
Closing if favour of #483 and tracking related work there.
