### ISSUE TITLE
Integration Testing With Spring-Boot + Spring-Shelll

### ISSUE THREAD

**Issue by jujoramos** [spring-projects/spring-shell#204]
Hello,

The workarounds suggested in #171 doesn't seem to work when using `spring-boot-2.0.0.RELEASE` + `spring-shell-2.0.0.RELEASE`, the tests just keep stuck at
```
WARN 11233 --- [           main] org.jline                                : Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information).
```
That said, I've been able to overcome the above by using the comments in #203:

```
@RunWith(SpringRunner.class)
@SpringBootTest(properties = {
    InteractiveShellApplicationRunner.SPRING_SHELL_INTERACTIVE_ENABLED + "=false",
    ScriptShellApplicationRunner.SPRING_SHELL_SCRIPT_ENABLED + "=false"
})
public class MyShellTests {

  @Autowired
  private Shell shell;

  @Test
  public void contextLoads() {
    Object help = shell.evaluate(() -> "help");
    assertThat(help).isNotNull();

    DefaultResultHandler resulthandler = new DefaultResultHandler();
    resulthandler.handleResult(help);
    System.out.println(help);

  }
}
```

However, the `DefaultHandler` fails because the internal `Terminal terminal` is `null`, so it's hard to do some real integration testing as `spring-shell` is not fully initialized. Is there any option available to execute a full test integration flow when using `spring-boot-2.0.0.RELEASE` + `spring-shell-2.0.0.RELEASE`?.
Cheers.

**Comment by jujoramos** [comment]
The following code works as an "integration test", but it's hacky and you need to get a reference to the terminal to execute all assertions... it'd be better for `spring-shell` to support integration testing out of the box.

```
  @Test
  public void testMyCommand() throws Exception {
    shell.run(new InputProvider() {
      private boolean invoked = false;

      @Override
      public Input readInput() {
        if (!invoked) {
          invoked = true;
          return () -> "myCommand";
        } else {
          return () -> "exit";
        }
      }
    });
  }
```
Any thoughts?.
Cheers.

**Comment by bharathcp** [comment]
check #221

**Comment by KyleRogers** [comment]
It's some time since you opened the issue but the problem is the `DefaultResultHandler` you're initializing in the `@Test` method. This does not work of course because the instance you're creating is not under control of spring (you've just created it yourself). But if you let spring wire an instance of `DefaultResultHandler` it works:

```java
@SpringBootTest(properties = {
        InteractiveShellApplicationRunner.SPRING_SHELL_INTERACTIVE_ENABLED + "=false",
        ScriptShellApplicationRunner.SPRING_SHELL_SCRIPT + ".enabled=false"
})
class AsciidocGeneratorTest {

    @Autowired
    private Shell shell;

    @Autowired
    private DefaultResultHandler resultHandler;

    @Test
    void contextLoads() {
        Object help = shell.evaluate(() -> "help");
        MatcherAssert.assertThat(help, is(not(nullValue())));

        resultHandler.handleResult(help);
        System.out.println(help);

    }

}
```

Please note the slight difference in modifiers and annotations because my example is using JUnit 5

**Comment by jvalkeal** [comment]
Closing if favour of #489 and tracking related work there.

**Comment by fmbenhassine** [comment]
Adding a reference to #1234 here FTR.
