### ISSUE TITLE
Enable tab completion when buffer is empty

### ISSUE THREAD

**Issue by Fitzoh** [spring-projects/spring-shell#210]
If you hit tab on a blank line, nothing happens.
It would be nice if a list of top level commands was generated as tab-completion options.

**Comment by Fitzoh** [comment]
Apparently the secret is to do this to the `lineReader` bean:
```
lineReader.unsetOpt(LineReader.Option.INSERT_TAB);
```

**Comment by ericbottard** [comment]
Nice find, thanks @Fitzoh !
