### ISSUE TITLE
Confirmation to proceed

### ISSUE THREAD

**Issue by hmble2** [spring-projects/spring-shell#213]
Is there an option in SpringShell to get confirmation from user before proceeding with command execution (for some selected/critical commands). For example, for command "Delete [appname]", I want user confirmation by displaying a message similar to "Are you sure you want to delete the app [appname]", and proceed only if user answers y/yes. How to achieve this in spring-shell ? Note: PCF CLI already does this, not sure if it uses spring-shell.

**Comment by kaskaz** [comment]
This is a good feature and i don't know if spring-shell implements it.

I was thinking about the _Confirmation_ annotation with the _question_ argument, with default YES/NO answer values. Or just those values to avoid complexity once it is for a binary decision propose.

It could be solved in the _resolve_ method of _StandardParameterResolver_ after parameter validation and before call _ValueResult_ :
1. Verifies if the called method is annoted with _Confirmation_ 
2. Prompt user for YES/NO (or y/n) input
3. Proceed to _ValueResult_  if YES, leave it if NO

regards

**Comment by ericbottard** [comment]
This can be easily implemented as part of the very first lines of your command implementation (possibly bypassing it with eg a `--force` argument is set) by reading from `System.in`.

This will not be implemented as a "built in" feature of Spring Shell.

**Comment by hmble2** [comment]
@ericbottard Hi Eric, thanks for reply, If I throw back some message back to the user in first few lines of my command "are you sure you want to delete [appname] ?" and user enters y/yes then : (1) how would the execution (control) come back to same command ? because user did not re-type whole command just y/yes. (2) When user entered y/yes and if control came to the command, would command still come with list of argument that user entered before entering y/yes...please clarify these two questions. Thanks

**Comment by ericbottard** [comment]
I'm not sure I understand the questions.

Just do something similar to this:

```java
@ShellMethod
public void detonateBomb(boolean force) {
  if (force || confirm()) {
    // blow it up
  }
}

private boolean confirm() {
  System.out.println("Are you sure you want to proceed?")
  String line = new LineNumberReader(new InputStreamReader(System.in)).readLine();
  return "y".equalgnoreCase(line);
}

```

**Comment by hmble2** [comment]
@ericbottard thanks, this solves my problem.

**Comment by hmble2** [comment]
@ericbottard Hello Eric, I used System.out.println in middle of my command execution as you suggested above...however the first character is not being captured...so if user types abcd, console only shows bcd and LineNumberReader also reads only bcd...however, once the command has been executed skipped character "a" is printed followed by prompt. A different problem, previously printed text using System.out.println is being spitted while executing a command even when that command doesn't system out anything. Any ideas what might be going wrong ? I feel System.out /System.in streams and jline input/output streams are going out of sync ? Do we have any alternate to using System.out.println ? Thanks for your help !

**Comment by ericbottard** [comment]
This is weird. Try flushing if possible, or even better I guess, inject and use JLine's `Terminal.writer()`
