### ISSUE TITLE
StandardParameterResolver + JCommanderParameterResolver

### ISSUE THREAD

**Issue by ms-xy** [spring-projects/spring-shell#215]
**Problem:**
Running StandardParameterResolver together with JCommanderParameterResolver results in errors if unnamed parameters are supplied.

**Description:**
In the class `org.springframework.shell/Shell.java` in the method `resolveArgs`, the following is done:
```java
for (ParameterResolver resolver : parameterResolvers) {
	for (int argIndex = 0; argIndex < args.length; argIndex++) {
		MethodParameter parameter = parameters.get(argIndex);
		if (args[argIndex] == UNRESOLVED && resolver.supports(parameter)) {
			args[argIndex] = resolver.resolve(parameter, wordsForArgs).resolvedValue();
		}
	}
}
```
As the list `wordsForArgs` is never modified ("consumed" values are not removed from the list), each resolver must parse the entire list again and again for each invocation of `resolve`.
The StandardParameterResolver correctly handles this situation by calculating the offset.
The JCommanderParameterResolver, however, does not.

**Expected Behavior:**
It should be possible to mix the StandardParameterResolver and the JCommanderParameterResolver for a command.

**Suggestions:**
- Either fix the JCommanderParameterResolver
- Or fix the way resolvers work (actually consume tokens instead of them remaining in the list)

**Comment by ms-xy** [comment]
I'd be willing to help with my suggested option number two, if you agree that this should be fixed.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
