### ISSUE TITLE
Don't hardcode log suffix in JlineAutoConfiguration

### ISSUE THREAD

**Issue by zebaslam** [spring-projects/spring-shell#220]
Seen [in this line](https://github.com/spring-projects/spring-shell/blob/master/spring-shell-core/src/main/java/org/springframework/shell/jline/JLineShellAutoConfiguration.java#L116)

Code from that area:
```
@Bean
public History history(LineReader lineReader, @Value("${spring.application.name:spring-shell}.log") String historyPath) {
	lineReader.setVariable(LineReader.HISTORY_FILE, Paths.get(historyPath));
	return new DefaultHistory(lineReader);
}

```

The suffix .log is hardcoded when the spring.application.name is provided not allowing the user to override this. If there is an alternative way of overriding this, please let me know.

**Comment by jujoramos** [comment]
Hello @zebaslam,

I'm overriding the default configuration by registering a custom `History` bean which takes a parameter containing the full path of the history file to use. If the value of the parameter is `disabled`, I just disable the history feature all together. The example is below:

```
  /**
   * Same as Spring-Shell default, but uses a custom filename.
   * @see JLineShellAutoConfiguration
   *
   */
  @Configuration
  public static class HistoryConfiguration {
    private final static String DISABLED = "disabled";
    @Autowired private History history;

    @Bean
    public History history(LineReader lineReader, @Value("${app.history.file}") String historyPath) {
      if (!DISABLED.equals(historyPath)) {
        lineReader.setVariable(LineReader.HISTORY_FILE, Paths.get(historyPath));
      }

      return new DefaultHistory(lineReader);
    }

    @EventListener
    public void onContextClosedEvent(ContextClosedEvent event) throws IOException {
      history.save();
    }
  }
```

Hope this helps.
Cheers.
