### ISSUE TITLE
Add public or protected constructor for `Table`

### ISSUE THREAD

**Issue by joeltoby** [spring-projects/spring-shell#225]
The [Spring Shell Table](https://github.com/spring-projects/spring-shell/blob/master/spring-shell-table/src/main/java/org/springframework/shell/table/Table.java) class has a single package private constructor which prevents it from being subclassed.

A `protected` or`public` constructor would be useful.

Is there a preferred method for creating custom tables?  For now, I've extended `TableModelBuilder` but directly extending `Table` would be a nicer implementation (client side).

I can make a PR to change the modifier on the constructor if that helps at all?  I just wanted to check first.

Thanks.

**Comment by jvalkeal** [comment]
Closing if favour of #483 and tracking related work there.
