### ISSUE TITLE
Sending command remotely from outside spring shell process

### ISSUE THREAD

**Issue by lemoncodes91** [spring-projects/spring-shell#228]
Im trying to find ways to send a command remotely from outside the spring shell process. Consider the use case below ; 

I have a Spring Shell application which has several commands defined(i.e `<command> <--first-param> <--second-param>` ). Then i want to execute that command inside a python code much like how paramiko will  be used in executing a command in say Linux.

Basically, i want to execute numerous commands to a running spring shell process. 

I have tried the non-interactive shell, it works, in a way, to my desired use case but it takes time to start the jar file everytime i want to execute a command. That is way i want the spring shell to start first den i execute, say 100 commands (remotely), then exits the spring shell. 

I was thinking maybe an IPC/MessageQueue but im not sure if im on the right path. 

Btw the "script" command does not fit my use case because i need to process the result on a per command basis. So if i execute the spring shell in 1 go( `java -jar myspring-shell.jar script /list/of/commands.txt`) i cannot filter out the result per command.

**Comment by lemoncodes91** [comment]
Im thinking of creating my own custome shell behaviour wherein instead of displaying a prompt it will wait for something like ang ipc message and execute shell based on that message. But im not sure if im on the right track

**Comment by ilx** [comment]
You could just wire it to the ssh or xtermjs

**Comment by lemoncodes91** [comment]
Well i successfully done it using rabbitmq but instead of using shell.run(), i used shell.execute(). Is there any way to override the .run() of shell?

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
