### ISSUE TITLE
Allow to use subcommands 

### ISSUE THREAD

**Issue by Antoniossss** [spring-projects/spring-shell#229]
I would like to have ability to group command so actual usage would look like:

`mygroupname myshellmethodname param1 param2....`

**Comment by ericbottard** [comment]
Your command names can contain spaces, so just make your command name `mygroupname myshellmethodname` and that should do the trick

**Comment by GJRTimmer** [comment]
Could you add this to the documentation. It was quite hard to find.

**Comment by izrobin** [comment]
But it does not allow for dynamic commands right?

```
mygroup repo1 push
mygroup repo2 push
```

for instance?
