### ISSUE TITLE
Consider picocli integration

### ISSUE THREAD

**Issue by remkop** [spring-projects/spring-shell#230]
Would there be any interest in integrating [picocli](https://github.com/remkop/picocli) in spring-shell?

Picocli has a number of features that may be interesting for spring-shell users:
* supports git-like [subcommands](https://picocli.info/#_subcommands) (and nested [sub-subcommands](https://picocli.info/#_nested_sub_subcommands))
* [usage help](https://picocli.info/#_usage_help) and  [version help](https://picocli.info/#_version_help) with [ANSI colors](https://picocli.info/#_ansi_colors_and_styles) 
* [TAB autocompletion](https://picocli.info/autocomplete.html) in bash and zsh
* API to easily create a [JLine](https://github.com/jline/jline2) `Completer`  ([example](https://github.com/remkop/picocli/releases#3.2.0-jline))
* easily [integrates with](https://github.com/remkop/picocli/releases#3.2.0-new) Dependency Injection containers
* programmatic and annotations parser API
* both  [named options](https://picocli.info/#_options) and [positional parameters](https://picocli.info/#_positional_parameters) can be  [strongly typed](https://picocli.info/#_strongly_typed_everything)
* [multi-valued fields](https://picocli.info/#_multiple_values) can specify an exact number of parameters or a [range](https://picocli.info/#_arity) (e.g., `0..*`, `1..2`)
* supports [Map options](https://picocli.info/#_maps) like `-Dkey1=val1 -Dkey2=val2`, where both key and value can be strongly typed
* components from the picocli Help API may be used to implement https://github.com/spring-projects/spring-shell/issues/202 text tables with ANSI colors

**Comment by jvalkeal** [comment]
I'm closing this because:

- picocli has its own ways to integrate with boot/spring
- both spring-shell and picocli has its own use cases and users
- we don't really like to rely on picocli as an external dependency to get circular dependency
- spring-shell has moved away from trying to provide common hooks to external cli libraries
