### ISSUE TITLE
Problem with cell alignments

### ISSUE THREAD

**Issue by ptitvert** [spring-projects/spring-shell#236]
I have the following code:

    public static String tableDisplay(Grid myGrid) {
        List<List<Integer>> myList = myGrid.getRawGrid();
        final int size = myList.size();

        String[][] data = new String[size][size];
        TableModel model = new ArrayTableModel(data);
        TableBuilder tableBuilder = new TableBuilder(model);

        for (int i = 0; i < size; i++) {
            for (int j = 0; j < size; j++) {
                Integer myValue = myList.get(i).get(j);
                data[i][j]=String.format("%5s", myValue==0?"":myValue.toString());

                TableBuilder.CellMatcherStub cell = tableBuilder.on(CellMatchers.at(i, j));
                cell.addAligner(SimpleHorizontalAligner.center);
                cell.addAligner(SimpleVerticalAligner.middle);
            }
        }

        return tableBuilder.addFullBorder(BorderStyle.fancy_double).build().render(80);
    }

and I get this output:

    ╔═════╦═════╦═════╦═════╗
    ║8    ║64   ║4    ║8    ║
    ╠═════╬═════╬═════╬═════╣
    ║4    ║8    ║16   ║4    ║
    ╠═════╬═════╬═════╬═════╣
    ║2    ║4    ║8    ║2    ║
    ╠═════╬═════╬═════╬═════╣
    ║8    ║4    ║2    ║2    ║
    ╚═════╩═════╩═════╩═════╝

The cell content is always left align, and not centered as I wanted (`SimpleHorizontalAligner.center`).
Am I doing something wrong? Or am I missing something?

I've done this code by looking at the [Table sample code](https://github.com/spring-projects/spring-shell/blob/master/spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/TableCommands.java )

And I am using either

        <dependency>
            <groupId>org.springframework.shell</groupId>
            <artifactId>spring-shell-starter</artifactId>
            <version>2.0.0.RELEASE</version>
        </dependency>

or

        <dependency>
            <groupId>org.springframework.shell</groupId>
            <artifactId>spring-shell-starter</artifactId>
            <version>2.0.1.BUILD-SNAPSHOT</version>
        </dependency>

without any success.

**Comment by jvalkeal** [comment]
Closing if favour of #483 and tracking related work there.
