### ISSUE TITLE
Expose @ShellMethod based on Spring profile or env variable

### ISSUE THREAD

**Issue by joeltoby** [spring-projects/spring-shell#239]
It would be useful to be able to expose / hide specific `@ShellMethod`s within a `@ShellComponent` based on an environment variable or Spring profile.

Is there a way to do this?  I've looked through the documentation but haven't found anything.

My use-case is simply to expose a 'simple' version of my complex Shell app for some users.

**Comment by jvalkeal** [comment]
I'm closing this in favour of #416 which I think is going to be a supported model of providing additional commands/options.
