### ISSUE TITLE
Mistake on web-page

### ISSUE THREAD

**Issue by ArtemZip** [spring-projects/spring-shell#247]
Hi,
You have mistake on page https://projects.spring.io/spring-shell/ .
I guess it should be  @ShellMethod("Translate text from one language to another.")

**Comment by seanbright** [comment]
And `Locale to` instead of `Locate to`

**Comment by Cjkjvfnby** [comment]
Hi, docs on https://projects.spring.io/spring-shell/ are outdated. 

Code example does not match with the latest specified version: `org.springframework.shell:spring-shell-starter:2.0.0.RELEASE`

```java
@ShellMethod("Translate text from one language to another.")
    public String translate(
      @ShellOption(mandatory = true) String text,
      @ShellOption(mandatory = true, defaultValue = "en_US") Locale from,
      @ShellOption(mandatory = true) Locate to
    ) {
      // invoke service
      return service.translate(text, from, to);
    }
```

And `2.0.1` is not a snapshot anymore. 

Example with all suggested fixes can looks like:
```java
package foo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.shell.standard.ShellComponent;
import org.springframework.shell.standard.ShellMethod;
import org.springframework.shell.standard.ShellOption;

import java.util.Locale;


@ShellComponent
public class TranslationCommands {
    private final TranslationService service;

    @Autowired
    public TranslationCommands(TranslationService service) {
        this.service = service;
    }

    @ShellMethod("Translate text from one language to another.")
    public String translate(
            @ShellOption() String text,
            @ShellOption(defaultValue = "en_US") Locale from,
            @ShellOption() Locale to
    ) {
        // invoke service
        return service.translate(text, from, to);
    }
}
```

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
