### ISSUE TITLE
Standard Quit/Exit does not work.

### ISSUE THREAD

**Issue by jlevy-bigfootbiomedical** [spring-projects/spring-shell#250]
I made a very small spring-shell application, but "exit" and "quit" do not actually cause the program to end.  It stops the "read execute" loop, but then just freezes.  The program does not print another prompt, nor does it end.
I replaced the Quit command with my own (based on System.exit) and that does work.
My code does not use threads or subprocesses, but it does connect to three different servers, but these are all stateless connections.  Some parts of my code are autowired, but others use standard Java new to create objects.
Am I missing a configuration option?  Or do I need to completely avoid creating "new" Java objects? Or is there something else I'm missing.
I'm using spring boot 2.1.2.RELEASE and spring shell 2.0.1.RELEASE.

Thanks for any help.

**Comment by ericbottard** [comment]
Are you sure the connection libraries you use don't use (daemon) threads in the background? Sounds like this is what is happening. If you're not happy with the System.exit() approach (which does the job after all), you could try to use a debugger to see what threads are still living after your command. You could also try to generate a [thread dump](https://stackoverflow.com/questions/4876274/kill-3-to-get-java-thread-dump) and see what is happening.

Hope that helps

**Comment by jlevy-bigfootbiomedical** [comment]
That helps a lot!  By experimenting with the thread dump, I do think the libraries that I'm using are keeping some threads around.  

If easy, I would add text similar to the following to the "Exitting the Shell" part of the Spring Shell Reference Documentation: https://docs.spring.io/spring-shell/docs/2.0.1.RELEASE/reference/htmlsingle/#built-in-commands

"The quit built in command will not exit the program if there are threads still running in the background."  And also possibly add sample code for a quit command which is more forceful.  Maybe by replacing the sample code in the "Overriding Specific Commands" section.

Also, you may want to change "Exitting the Shell" to Exiting the Shell", which I think is more standard.

I'm happy to do a pull request for this work, if you think it is worthwhile.  I've never done a Spring pull request, so I don't know if that is a reasonable thing to do.

**Comment by ericbottard** [comment]
We're always happy to receive PRs, of course! Feel free to send one along, I'm sure it is going to be merged quickly, as the feedback you sent above is definitely valuable.

**Comment by sathomps** [comment]
On the same subject, I would like to have a custom ThrowableResultHandler to handle inputs like `ctrl+c` and actually exit the system.  I know [others ](https://stackoverflow.com/questions/55037587/how-to-apply-custom-resulthandler-in-spring-shell) are looking for this feature as well.  

Without having a @ConditionalOnMissingBean present on the ResultHanderConfig bean methods, I'm not seeing a way to accomplish this.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
