### ISSUE TITLE
Add additional lifecycle hook `afterStartup()`

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-shell#252]
At times a user may need to execute custom code at startup of the shell depending on the command line parameters. For example, the application may ask the user for credentials etc. It would be best to trigger those steps after the banner has been printed. Currently the only lifecycle hooks to achieve this is:

`org.springframework.shell.core.JLineShell#getStartupNotifications()`

While this works, this hook is not appropriately named. Should we maybe add another hook? E.g. `void afterStartup()`?

We would also need to be smarter then with some of the other hooks, e.g. `setPromptPath(null);`. For example the visual appearance of the prompt may be different, based on the outcome of the executed custom code.

**Comment by ghillert** [comment]
Special consideration has to be take for .... in `Bootstrap#run()` we allow for `commandLine.getShellCommandsToExecute()` which will not invoke the lifecycle methods of the Shell.

**Comment by ghandhikus** [comment]
This seems to be related to my issue. I tried to hook Spring Shell to already finished Spring Boot application and found out it doesn't use Lifecycle class at all. Any solutions to this? I can't find anything on the internet to how to wire Lifecycle interface with Spring Shell. Just this page.

**Comment by Antoniossss** [comment]
You can use listen for context refreshed event - it is right after application starts and is ready to go.

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
