### ISSUE TITLE
ExecutionProcessor is not called, documentation might be to short

### ISSUE THREAD

**Issue by xlf12** [spring-projects/spring-shell#28]
Implementing the following I can see the interceptor is not called. The bean will be created, there is no scanning issue. I would expect the interceptor will be called before every command. A debug session at `SimpleExecutionStrategy` line 44 showed that there is no `ExecutionProcessor` in the `ParseResult`. Following the interceptor couldn't  be called this way ?!

Example code:

``` java
@Component
public class CommandInterceptor implements ExecutionProcessor {

    /**
     * @see org.springframework.shell.core.ExecutionProcessor#beforeInvocation(org.springframework.shell.event.ParseResult)
     */
    @Override
    public ParseResult beforeInvocation(ParseResult invocationContext) {
        for (Object argument : invocationContext.getArguments()) {
            System.out.println(argument);
        }
        return invocationContext;
    }
    …
}
```

**Comment by ericbottard** [comment]
Tidying old 1.x issues
