### ISSUE TITLE
Multiple file by-name parameters syntax does not work 

### ISSUE THREAD

**Issue by vavrfam** [spring-projects/spring-shell#282]
With `ShellMethod`s,  where there are multiple File type method parameters, invoking  by-name parameters does not work .
 Lets say there is one input and one output file, invoking the parameter by `--paramName paramValue` does not work.  But `paramName paramValue` works. 
But for consistency purposes we need `--paramName paramValue` syntax to work.

Example code:

```
@ShellComponent
public class TestShell {

    @ShellMethod(key = "invoke", value = "Invoke something")
    public void invoke(
            @ShellOption(value = "inputFile", defaultValue = ShellOption.NULL, help = "JSON file") File inputFile,
            @ShellOption(value = "outFile", defaultValue = ShellOption.NULL, help = "JSON file") File outFile) {

        System.out.println("inputFile = [" + inputFile + "], outFile = [" + outFile + "]");

    }
}
```

What does not work: 
```
invoke --inputFile /test --outFile /test

```

What works:
```
invoke inputFile /test outFile /test
```

Appreciate any feedback. Thank you!!

**Comment by c4deszes** [comment]
By default every parameter can be named using the method argument name with '--' prefix, but once you add your own `@ShellOption` annotation with the `value` field overwritten, the new keys are going to be the ones you specified. 

The value field is actually an array, this is meant to allow shorter keys, like 
`@ShellOption(value = {"-k", "--key"})`. Also notice that the `value` field has an empty array as default value, so you can use `@ShellOption` to assign arity but leave keys intact.

The keys you specify always have to be prefixed manually. If you don't specify them but wish to overwrite the prefix you can use `@ShellMethod.prefix`.

But these are all written here: [Spring Shell Reference](https://docs.spring.io/spring-shell/docs/current-SNAPSHOT/reference/htmlsingle/#_customizing_the_named_parameter_key_s)
