### ISSUE TITLE
How to override ThrowableResultHandler

### ISSUE THREAD

**Issue by roman-finix** [spring-projects/spring-shell#303]
I want to make shell execution to be completely non-interactive, 
`java -Dspring.shell.interactive.enabled=false -Dspring.shell.script.enabled=true  -jar ../my-shell/build/libs/my-shell-1.0.0-SNAPSHOT-boot.jar @/var/tmp/my-cmd.txt`

content of `/var/tmp/my-cmd.txt` is `doSomeAction`

command execution works fine, but when if it fails with exception , exception is not printed (because it shell print it only by command "stacktrace").

Not sure what for such "interactive" mode to see result is required by default ...
I need to change this in my app and print any exception right after execution (to be real shell mode, as all other bash/shell tools do this).
So I need to override  ThrowableResultHandler and do custom handling
```
package com.xxx;

import org.springframework.shell.result.ThrowableResultHandler;
import org.springframework.stereotype.Component;

@Component
public class MyThrowableResultHandler extends ThrowableResultHandler {
  @Override
  protected void doHandleResult(Throwable result) {
    super.doHandleResult(result); // just do the same for simplicity 
  }
}
```
But this result in:
```
Caused by: java.lang.IllegalArgumentException: 
 Multiple ResultHandlers configured for class java.lang.Throwable: 
both com.xxx.MyThrowableResultHandler@33a1bb90
and  org.springframework.shell.result.ThrowableResultHandler@7d5f59b4
at org.springframework.shell.result.TypeHierarchyResultHandler.registerHandler(TypeHierarchyResultHandler.java:80)
at org.springframework.shell.result.TypeHierarchyResultHandler.setResultHandlers(TypeHierarchyResultHandler.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
``` 

Looks like it all due to:
https://github.com/spring-projects/spring-shell/blob/master/spring-shell-core/src/main/java/org/springframework/shell/result/ResultHandlerConfig.java 
https://github.com/spring-projects/spring-shell/blob/master/spring-shell-core/src/main/java/org/springframework/shell/result/TypeHierarchyResultHandler.java#L77

So overrides is not allowed ...
Is it by design if yes .... how can we can use custom `ResultHandler<Throwable>` ?

**Comment by xlf12** [comment]
One solution which might help is to use Spring AOP to handle results or exceptions, e.g.

1. in Spring Boot add the AOP Support 

```XML
   <dependency>
       <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-aop</artifactId>
   </dependency>`
```
2. Write the Aspect 

```Java
@Aspect
@Component
public class ExceptionHandlingAspect {

    @Around(value = "@annotation(org.springframework.shell.standard.ShellMethod)")
    public Object handleMethodCall(ProceedingJoinPoint joinPoint) throws Throwable {
       // do something useful here 

       try {
          Object proceed = joinPoint.proceed();
        } catch (Throwable t ) {
             // handle error here 
        }
        // do something useful here 
        return proceed
   }
```

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
