### ISSUE TITLE
Is this project still alive ? 

### ISSUE THREAD

**Issue by slavus** [spring-projects/spring-shell#304]
Is this project still alive ? 
There was no progress for couple of years now ?

**Comment by c4deszes** [comment]
There's no official response, but it's not on Spring Initializr anymore so I think that's a sign in itself. Also see this recent thread #302

**Comment by onobc** [comment]
It is alive and there are a few of us actively working on this project recently with an upcoming `2.1` release w/ support for Spring Boot 2.6/Spring5.3. We will then focus on a `3.x` release supporting SB3/SF6 (talked about in #365).

**Comment by jvalkeal** [comment]
Closing this and sorry that it was stale for way too long time.
