### ISSUE TITLE
Is Spring shell alive or dead ?

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [spring-projects/spring-shell#313]
I was eager to use spring shell to build one of interactive cli for my org. I want to confirm if this project is still alive. I dont see it on start.spring.io

**Comment by orange-guo** [comment]
I think this project is dead, there are too many questions without answers, you can consider using other libraries, or if you don't have too many custom requirements, you can still use this library, until today I have not encountered a big bug

**Comment by tpavel-aspose** [comment]
This is a good product. It needs for us

**Comment by jvalkeal** [comment]
We had trouble to do maintenance but good news is that we've just released first milestone from 3.0.x line.
