### ISSUE TITLE
Circular dependency breaks spring-shell with spring-boot 2.6.x

### ISSUE THREAD

**Issue by t0mdev** [spring-projects/spring-shell#338]
After upgrading spring boot 2.6.x, the following error occurs with spring shell:

```
Exception encountered during context initialization - cancelling refresh attempt: 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.shell.result.ResultHandlerConfig': Invocation of init method failed; 
nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: 
Error creating bean with name 'org.springframework.shell.result.ResultHandlerConfig': 
Requested bean is currently in creation: Is there an unresolvable circular reference?
```

This pops up now, because spring boot 2.6.0 prohibits circular dependencies by default. 

Sample project: https://github.com/t0mdev/spring-shell-circular-dependency/blob/main/build.gradle

Could you resolve the circular dependency? 

A temporary workaround is to overwrite the spring-boot default: `spring.main.allow-circular-references: true`.

**Comment by jvalkeal** [comment]
This is a dup of #324
