### ISSUE TITLE
Have Shell Play Nice With Spring Boot

### ISSUE THREAD

**Issue by kurron** [spring-projects/spring-shell#34]
I've tried combining Spring Boot and Spring Shell because I liked how Spring Boot can create a nice self-contained executable JAR.  What I found was that both projects create competing Spring contexts.  I've tried a couple different hacks with less than satisfactory results.  It would be nice if Spring Shell and Spring Boot were aware of each other so that we could write nice shell-based tools and get all the Spring Boot goodness as well.

**Comment by hansvanbeneden** [comment]
This article was helpful to me: 
http://blog.comsysto.com/2014/12/22/spring-shell-an-easy-way-to-create-your-own-shell/

**Comment by jeffellin** [comment]
I have gotten this to work by hacking the BootStrap class a bit.

https://github.com/jeffellin/springshellwithboot

**Comment by kpb** [comment]
I would love this feature also - make it easy to bootstrap a spring-shell app with spring-boot. No shims or other hacks.

**Comment by linux-china** [comment]
Based on @jeffellin  code, I created a spring-boot-starter-shell to make spring shell with spring-boot easy.   https://github.com/linux-china/spring-boot-starter-shell

**Comment by ericbottard** [comment]
Closing as addressed for Shell 1 (see above). Spring Shell 2 plays nicely with Boot out of the box
