### ISSUE TITLE
Change or remove group of "Built-in Commands"

### ISSUE THREAD

**Issue by dhait** [spring-projects/spring-shell#347]
When the user types "help", the Built-In Commands are always shown as a separate group, followed by a group of my own commands (named after the class they are in).

I would like to see all the commands together, with no distinction.  But there doesn't appear to be a way to "ungroup" all the commands, or alternatively merge the groups together.

Can we get some more flexibility on the Built-In commands (short of having to redefine every one of them)?

**Comment by jvalkeal** [comment]
Yes I've also felt that being a bit annoying. We could try to allow defining on what group those belong to and then going even further and omitting group name if there's only one.

**Comment by jvalkeal** [comment]
@dhait Would you be happy with changes in a PR?
