### ISSUE TITLE
Please upgrade hibernate-validator(6.0.18.Final) to latest or any non-vulnerable version, as its coming as transitive dependency of it.

### ISSUE THREAD

**Issue by amanmishra** [spring-projects/spring-shell#349]
![image](https://user-images.githubusercontent.com/5356977/150092358-76c01d81-428e-43de-974a-d6453b4e19a1.png)

I have checked for “spring-shell-starter – 2.0.1-RELEASE” also that if there is any scope of upgrading this. But we can’t do any upgrade there because we are already on latest.

![image](https://user-images.githubusercontent.com/5356977/150092293-7fe24b52-7b06-48dc-81bb-f3c8ba9b55b7.png)

**Comment by amanmishra** [comment]
we are using the below plugin to combine all the dependencies regarding spring-shell-starter-2.0.1.RELEASE. So please tell me how can we overwrite this hibernate-validator jar version in this.

**Comment by jvalkeal** [comment]
This is resolved in `3.0.x` line which gets deps from latest Boot versions and we just got first milestone out. `2.0.x` line is not maintained anymore but you can do normal maven/gradle dance to force that validator version.
