### ISSUE TITLE
Support for Spring Boot 3/Framework 6 any time soon?

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-shell#365]
This project (still) relies on javax.validation not the jakarta namespace. Is there a branch, so we can use Spring Shell for SB3?

**Comment by jvalkeal** [comment]
Plan is to get `2.1.0` released and then move main branch into boot 3.x. We just want avoid having two branches on an active development mode.

**Comment by jvalkeal** [comment]
Release `2.1.0` is out and main branch is on Boot 3.x snapshots. Hopefully it will not take that much time to get first milestone out from it. In light of that I'm closing this.
