### ISSUE TITLE
Drop jcommander

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-shell#395]
For now leading to `2.1.x` remove support for `com.beust.jcommander`. It doesn't provide that much value and has been problematic for stories to have graalvm support.

We may think to bring back better support model for adapters if there is a need for those. Thus, for now lets remove it.

**Comment by grahambrown11** [comment]
I just got the latest snapshot and now my project doesn't start - the autoconfigure spring.factories refs a now deleted class: `org.springframework.shell.boot.JCommanderParameterResolverAutoConfiguration`

**Comment by jvalkeal** [comment]
@grahambrown11 thx, just pushed a fix.
