### ISSUE TITLE
Using the default port regardless the port configuration when ...

### ISSUE THREAD

**Issue by vw98075** [spring-projects/spring-shell#397]
In the application.yml, I have

    server:
       port: 8081
When I run the app on Idea, the customized port is used.

When I run the same app on the command line with

    java -jar target/.....

The app will use the default port 8080.

Here is the related part of my pom.xml:
```
		<dependency>
			<groupId>org.springframework.shell</groupId>
			<artifactId>spring-shell-starter</artifactId>
			<version>2.1.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.shell</groupId>
			<artifactId>spring-shell-starter-jna</artifactId>
			<version>2.1.0-SNAPSHOT</version>
		</dependency>
```

**Comment by jvalkeal** [comment]
Not sure if there's any reason to mix shell app with a web container. Most likely your yml is not packaged to a jar as classpath is usually different within IDE's.
