### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-shell#433]
- [x] options labels #424
- [x] theme changes #442
- [x] completion changes #449
- [x] Flatten Using Spring Shell section

**Comment by timtebeek** [comment]
Could you add documentation for "Providing TAB Completion Proposals" & "Testing"? I'm having some trouble finding their expected usage from the documentation & existing tests.

**Comment by jvalkeal** [comment]
Good point as completion docs are missing as we just made a rework for that a week ago. Testing is a big area for improvements as I've struggled with it myself as well.

**Comment by jvalkeal** [comment]
Not yet
