### ISSUE TITLE
support noninteractive usage

### ISSUE THREAD

**Issue by alexanderankin** [spring-projects/spring-shell#441]
would this project be interested in supporting a standard way to invoke spring-shell based apps non-interactively? I can't imagine a use case where the end user of this library is actually happy without this functionality. interactive shell + autocomplete is great for discovery, but after I've discovered what I need to do, i would want to automate it, right?

> Not all applications need a fancy web user interface! Sometimes, interacting with an application using an interactive terminal is the most appropriate way to get things done.

This seems to assume an expert user, but then prevents the expert user from doing what they normally do (automate/script things).

This also seems to go hand in hand with #323

**Comment by jvalkeal** [comment]
Actually we have a non-interactive functionality currently in `2.1.x` snapshots. You can try `spring-shell-samples` to give parameters to jar and enters non-interactive mode. `-Pnative` also builds graal binary. We're in a process of making docs better on these things.

There's also interactive things(i.e. selectors and questions) possible within commands itself and this is one area which we're trying to tackle and make better. It's kinda same issues like in github cli where commands should not ask any user input if there is no tty.

**Comment by alexanderankin** [comment]
ok, i won't belabor this issue then, it was in the context of a specific project, which I will have to do more research on

(i can't even tell what version of spring shell its using since the spring shell starter is not listed in any of the parent poms in the repo, nor in _spring-boot-_ or _spring-cloud-_ 'dependencies' (boms)).
