### ISSUE TITLE
Missing option error without ShellOption

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-shell#446]
I was replicating the very basic shell component https://github.com/spring-projects/spring-shell/blob/main/spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/Commands.java 

```
@ShellComponent
public class FsCommands {
 @ShellMethod("Add numbers.")
  public int add(int a, int b, int c) {
    return a + b + c;
  }
}
```

and got an error:

```
shell:>add 1 2 3
Missing option, longnames='a', shortnames=''
Missing option, longnames='b', shortnames=''
Missing option, longnames='c', shortnames=''
```

**Comment by jvalkeal** [comment]
I know that older shell used to work like that and we're still thinking how to handle these corner cases. We're now forcing a better model to define how these plain methods are translated to command registration. For now you need to define arity so that shell knows what to consume.

```
add(@ShellOption(arity = 1) int a, @ShellOption(arity = 1) int b, @ShellOption(arity = 1) int c)
```

**Comment by ullenboom** [comment]
Your own examples still don't work with the release candidate.

```
my-shell:>add 1 2 3
Missing option, longnames='a', shortnames=''
Missing option, longnames='b', shortnames=''
Missing option, longnames='c', shortnames=''
```

I think this is important to get it right.
