### ISSUE TITLE
DynamicCommands does not work in 2.1.0-M5

### ISSUE THREAD

**Issue by kidomine** [spring-projects/spring-shell#456]
I was playing with dynamic commands using the spring shell samples (see https://github.com/spring-projects/spring-shell/blob/main/spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/DynamicCommands.java) and I noticed that I cannot get it to work.

Below is the sample output form this example, built directly from `2.1.0-M5` branch:
```shell
❯ java -jar .\spring-shell-samples-2.1.0-M5.jar
::
my-shell:>blow-up
Boom!
my-shell:>connect
my-shell:>authenticate --credentials sesame
my-shell:>blow-up
Boom!
my-shell:>
my-shell:>
```

I added some logs in the `blowUp` command to print `connect` and `authenticate` and below is the result:
```shell
❯ java -jar .\spring-shell-samples-2.1.0-M5.jar
::
shell:>blow-up
connected=false
authenticated=false
Boom!
shell:>connect
shell:>authenticate --credentials sesame
shell:>blow-up
connected=true
authenticated=true
Boom!
shell:>
```

It seems half of the issue is not reproducible in `2.1.0-M3`. When the `help` command is executed, I get the following result for `Dynamic Commands`:
<table>
    <tr>
        <th>2.1.0-M3</th>
        <th>2.1.0-M5</th>
    </tr>
<tr>
    <td>
        <pre>
Dynamic Commands
       *authenticate: Authenticate with the system
       blow-up: Blow Everything up
       connect: Connect to the system
       disconnect: Disconnect from the system
        </pre>
    </td>
    <td>
        <pre>
Dynamic Commands
       disconnect: Disconnect from the system
       authenticate: Authenticate with the system
       blow-up: Blow Everything up
       connect: Connect to the system
        </pre>
    </td>
</tr>
</table>

Notice how there is an `*` in the `authenticate` for `2.1.0-M3` indicating that it is initially disabled. However, this is not the case for `2.1.0-M5` . Note that I haven't tested the behavior in `2.1.0-M4`.

Executing `authenticate` in `2.1.0-M3` works as expected, i.e.:
```shell
my-shell:>authenticate
Command 'authenticate' exists but is not currently available because you are not connected
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
```

### Clarification for 2.1.0-M3:

By default, `blowUp` does not work properly in `2.1.0-M3`. It turns out this is an error in the sample as there is no implementation for `dangerousAvailability`.
However, after adding implementation for `dangerousAvailability`, `blowUp` works as expected:
```java
public Availability dangerousAvailability() {
        return connected && authenticated ? Availability.available()
                : Availability.unavailable("you failed to authenticate. Try 'sesame'.");
    }
```

Given this information, it appears that `ShellMethodAvailability` and `xxxAvailability` are both not respected in `2.1.0-M5`.
It would be great if someone could have a look at this.

**Comment by jvalkeal** [comment]
Did you try main or 2.1.0-RC1 as there was #423 which had fixes for dynamic commands.

**Comment by kidomine** [comment]
I did not realize there was an RC1. I can confirm that the behavior is OK in 2.1.0-RC1.
Thank you!
