### ISSUE TITLE
Help should group commands with aliases

### ISSUE THREAD

**Issue by kidomine** [spring-projects/spring-shell#458]
I noticed that in `2.1.0-RC1`, shell methods with multiple keys are presented differently when `help` is invoked.
For example:
```java
@ShellMethod(key={"key1", "key2"}, value = "Command that does something")
public String doSomething()
{
    // do something
}
```

Below is the comparison of output when typing `help`:
<table>
    <tr>
        <th>2.1.0-M5 (and earlier)</th>
        <th>2.1.0-RC1</th>
    </tr>
    <tr>
        <td>
            <pre>
Sample Commands
    key1, key2: Command that does something
            </pre>
        </td>
        <td>
            <pre>
Sample Commands
    key1: Command that does something
    key2: Command that does something
            </pre>
        </td>
    </tr>
</table>

In `2.1.0-RC1`, the command description is repeated for each key. This makes the `help` output look cluttered. This can quickly get confusing if the developer intentionally had commands that have similar descriptions.

Is this new behavior intentional?
Is it possible to bring back the behavior similar to that of `2.1.0-M5` and earlier?

**Comment by jvalkeal** [comment]
Thanks for pointing this out as I think it's an oversight when help content got changed from hardcoded output into templated output(which user could change).
