### ISSUE TITLE
ShellOption naming change 2.1.0-RC1 

### ISSUE THREAD

**Issue by mjeffrey** [spring-projects/spring-shell#460]
In 2.0.1 the shell option names were kebab cased, in 2.1.0-RC1 they are now camelCase

For example:

`
@ShellOption boolean withBalance
`

In 2.0.1 this option was `with-balance`
In 2.1.0-RC1 this is now `withBalance`

Please close this if it is an intended change. Of course the value can be set explicitly: 
e.g. `@ShellOption("--with-balance")`.

A testcase may be found here (see README.md for how to run it in each version):
https://github.com/mjeffrey/spring-shell-testcase

**Comment by jvalkeal** [comment]
Ah I didn't realise it used to work like that as I think where we used shell option name was always defined. Looking old code it used to unCamelify names even if `@ShellOption` says parameter name is used on default.

https://github.com/spring-projects/spring-shell/blob/c3cfca6a9ce13adeed9b3101ad577613535ad97f/spring-shell-standard/src/main/java/org/springframework/shell/standard/ShellOption.java#L54

I'd say that was a bug and now works as documented?

**Comment by mjeffrey** [comment]
Looks that way - thank.
btw how should I go about making some suggestions for release 3? 
I'd like to see a number of cases supported that are quite difficult at the moment.
