### ISSUE TITLE
ShellOption booleans are now mandatory in 2.1.0-RC1

### ISSUE THREAD

**Issue by mjeffrey** [spring-projects/spring-shell#461]
For the option
```
@ShellOption boolean withBalance
```
In 2.0.1 this option was optional (and set to false if not supplied)
```
shell:>account
iban=null, with-balance=false
```
```
shell:>account --with-balance
iban=null, with-balance=true
```

In 2.1.0-RC1 this is mandatory, so you need to write: `--withBalance false`
```
shell:>account
Missing option, longnames='withBalance', shortnames=''
```

A testcase may be found here (see README.md for how to run it in each version):
https://github.com/mjeffrey/spring-shell-testcase

**Comment by jvalkeal** [comment]
Well they are not, however looks like we don't properly handle this case for annotation when backing option within registration is created. With `@ShellOption(defaultValue = "false") boolean arg1` it works as expected.

In older shell these were not very well tested and it's good that we're now getting more reports of these issues.

I think question is if it's safe to assume `false` for `boolean` if no defaults are defined as currently not defining a default is forcing that argument to be mandatory?

With `3.x` we're probably going to get new annotations which would align much better with new `CommandRegistration` and keep existing old `@ShellOption` as close as it used to work with `2.0.x`. That would implicate that we force `false` for this use case and possibly user will lose a way to make it mandatory.

What do you think?
