### ISSUE TITLE
Handy additions for interactive mode

### ISSUE THREAD

**Issue by mcseemz** [spring-projects/spring-shell#469]
Hey, respect to developers.

Spring Shell in interactive mode turned out to be handy for text-based games. But there are two cases that make things more complex than desired:

1. Component Flow for multiple item selector  (`.withMultipleItemSelector`) cannot control the initial selection state for `selectItems`. `selectItems` always appear deselected for the user.
2. It is not possible to have command already suggested in the shell input. e.g. `shell:>start`, with further control over suggestions depending on the current application state.

If that can be addressed, would make life a little easier.
Thanks!

**Comment by jvalkeal** [comment]
1. It's worked on pr #468
2. As we're first completing commands(those are known from command registry) and then command options(which can be customised).

Not sure about programmatic suggestion without user interaction as I hear about an idea first time. Depends if jline has some features around it.
