### ISSUE TITLE
Spring Shell log file location not changed

### ISSUE THREAD

**Issue by ateequrrahman97** [spring-projects/spring-shell#478]
Hi @ericbottard,
I hope you are doing good

I have added these two lines in my properties file to change the spring shell log file location but it does not create/save in my desired location and file.
It saves on the root of the project directory with my project name.

`spring.shell.config.location=./logs`
`spring.shell.history.name=shell-command.log`

Here is the Reference link [Spring Shell History](https://docs.spring.io/spring-shell/docs/2.1.0-SNAPSHOT/site/reference/htmlsingle/#_history)

**Comment by jvalkeal** [comment]
This feels like regression. We'll take a look.

**Comment by nad33mahm3d** [comment]
I am also facing the same issue. I am using below dependency
`<dependency>
			<groupId>org.springframework.shell</groupId>
			<artifactId>spring-shell-starter</artifactId>
			<version>2.0.1.RELEASE</version>
		</dependency>`

**Comment by jvalkeal** [comment]
@ateequrrahman97 can you tell spring shell version?

**Comment by ateequrrahman97** [comment]
> @ateequrrahman97 can you tell the spring shell version?

@jvalkeal yes
Its
2.0.1.RELEASE

**Comment by jvalkeal** [comment]
Right you referenced 2.1.0-SNAPSHOT docs so it should work there.

**Comment by ateequrrahman97** [comment]
> Right you referenced 2.1.0-SNAPSHOT docs so it should work there.

But On maven, there are only two versions available!
[Mavan Repository](https://mvnrepository.com/artifact/org.springframework.shell/spring-shell-starter)

And 2.1.0-SNAPSHOT does not load and gives me an error.

Unresolved dependency: 'org.springframework.shell:spring-shell-starter:jar:2.1.0-SNAPSHOT'

**Comment by ateequrrahman97** [comment]
> Right you referenced 2.1.0-SNAPSHOT docs so it should work there.
Hi @jvalkeal 

I have created a new project but face the same issue.

Dependency 'org.springframework.shell:spring-shell-starter:2.1.0-SNAPSHOT' not found

**Comment by jvalkeal** [comment]
That's because 2.1.0 is not yet released(milestones and snapshots only available from spring repos). Just about to do it by next week.

**Comment by ateequrrahman97** [comment]
> That's because 2.1.0 is not yet released(milestones and snapshots only available from spring repos). Just about to do it by next week.

Thanks @jvalkeal 
So do not close the issue until the new release.
And it would be great if you comment here after the new release.

**Comment by jvalkeal** [comment]
@ateequrrahman97 `2.1.0` is out and in maven central.
