### ISSUE TITLE
Positional Parameters not working in latest version

### ISSUE THREAD

**Issue by rcgallagher** [spring-projects/spring-shell#479]
It seems that between versions 2.0.1.RELEASE and 2.1.0-RC1, positional parameters stopped working. I've tested with spring-boot-starter-parent 2.5.14 and 2.5.7.

See my [example project](https://github.com/rcgallagher/spring-boot-shell-example) for reference.

For Java build & test: `mvn clean install && java -jar target/springbootshellexample-1.0-SNAPSHOT.jar`

**Comment by jvalkeal** [comment]
There was some fixes in https://github.com/spring-projects/spring-shell/issues/446.  You should try snapshots or show actual behavior.

**Comment by jvalkeal** [comment]
Closing this, feel free to re-open if recent release 2.1.0 doesn't work.

**Comment by rcgallagher** [comment]
Confirmed working in the latest snapshot
