### ISSUE TITLE
PathInput for existing directories

### ISSUE THREAD

**Issue by timtebeek** [spring-projects/spring-shell#497]
Spring Boot Migrator has a `scan` option where users enter an existing directory. At first glance `PathInput` seemed a good fit, but almost immediately we saw it's [hardcoded to exclude existing directories](https://github.com/spring-projects/spring-shell/blob/v2.1.0/spring-shell-core/src/main/java/org/springframework/shell/component/PathInput.java#L145). And since `checkPath` is private, it's not easy to adjust this behaviour.

How would you recommend we ask users to input an existing directory?
And is this something to contribute back here?

I could see a number of options:

1. Make `checkPath` protected, with an override dropping the directory requirement.
2. Add a flag argument on whether to allow directories
3. Add an argument to test/filter files for applicability
4. Fully new `DirectoryInput` flow component
5. Stick with `@ShellOption` valueProvider
6. Nothing in spring-shell; users should implement their own component.
7. Others?

Any input much appreciated. :)

**Comment by jvalkeal** [comment]
There discussion https://github.com/spring-projects/spring-shell/discussions/474 to see where to take that component.

**Comment by jvalkeal** [comment]
I've been experimenting with a new component `PathSearch` which is loosely based on ideas stolen from https://github.com/junegunn/fzf. User gives a `base path` for search and then optional `pattern` for matching/limiting results. Here's a screencast how this idea works in my wip branch.

![component-path-search](https://user-images.githubusercontent.com/50398/194045060-4afe5df5-ce99-482c-8e81-eb3064f36bc3.gif)

**Comment by jvalkeal** [comment]
I'm closing this if favour of #556.
