### ISSUE TITLE
CompletionProposal with complete

### ISSUE THREAD

**Issue by fonimus** [spring-projects/spring-shell#512]
Hello, I am providing in my application an ExtendedFileValueProvider which does not stop if comes a directory (i.e. the completion proposal is not complete). Today I had to extended some classes to do this, and I am wondering if it could be included in spring shell.

The aim is to add `complete` boolean field in `CompletionProposal` in order to be able to get this value in `CompleterAutoConfiguration.CompleterAdapter#complete` :

````
proposals.stream()
				.map(p -> new Candidate(
					p.dontQuote() ? p.value() : cpl.emit(p.value()).toString(),
					p.displayText(),
					p.category(),
					p.description(),
					null,
					null,
					true) --> here we can set p.complete() instead of true
				)
				.forEach(candidates::add);
````

This way the class implementing `ValueProvider` can decide if the proposal is complete or not.
Do you think it could be an improvement in spring shell library ?

Thanks a lot !

**Comment by jvalkeal** [comment]
Do you have screenshot or something similar to show how it looks like?

**Comment by fonimus** [comment]
Sure !
In this gif example I have written the following command :

````
@ShellMethod("File command")
public void file(
            @ShellOption(valueProvider = FileValueProvider.class, defaultValue = ShellOption.NULL) File file,
            @ShellOption(valueProvider = ExtendedFileValueProvider.class, defaultValue = ShellOption.NULL) File extended
) {
        info(file);
        info(extended);
}
````

and we can see that when I set complete=false, the cursor stays put and I can press tab again to follow path ; if I use existing file provider I have to press del key to go back and then press tab.

![extended-file-provider](https://user-images.githubusercontent.com/26186612/186601563-e53237f0-b076-4edb-8c71-390e38f3afd6.gif)

**Comment by jvalkeal** [comment]
That would be nice addition. If you have a time please make a PR and we can continue from there!

**Comment by tincore** [comment]
@jvalkeal Just created this quick PR for this issue. https://github.com/spring-projects/spring-shell/pull/715

Not to diverge too much. I think that positional parameters do not autocomplete with tab. is this intended?
