### ISSUE TITLE
Unable to post process non-interactive output with bash commands

### ISSUE THREAD

**Issue by lonhutt** [spring-projects/spring-shell#52]
I have a need to be able to process the output of a custom CLI (written with spring-shell) with standard bash commands like 'cut', 'sort', 'uniq', etc. when executing commands in non-interactive mode.

Currently there are two issues:
1. every command executed in non-interactive mode prints a line that looks something like:
`Dec 03, 2014 5:25:39 PM org.springframework.shell.core.AbstractShell handleExecutionResult`
2. it appears that the log formatter is stripping `tab` characters from the output even though that's what i am returning from the various commands.

I was able to work around both of these issues by applying the following changes:

``` java
diff --git a/src/main/java/org/springframework/shell/Bootstrap.java b/src/main/java/org/springframework/shell/Bootstrap.java
index 35d397e..0af509c 100644
--- a/src/main/java/org/springframework/shell/Bootstrap.java
+++ b/src/main/java/org/springframework/shell/Bootstrap.java
@@ -16,7 +16,11 @@
 package org.springframework.shell;

 import java.io.IOException;
+import java.util.logging.ConsoleHandler;
+import java.util.logging.Formatter;
+import java.util.logging.Handler;
 import java.util.logging.Level;
+import java.util.logging.LogRecord;
 import java.util.logging.Logger;

 import org.springframework.beans.factory.support.DefaultListableBeanFactory;
@@ -153,7 +157,22 @@ public class Bootstrap {
        if (null != commandsToExecuteAndThenQuit) {
            boolean successful = false;
            exitShellRequest = ExitShellRequest.FATAL_EXIT;
-
+
+           for(Handler h : Logger.getLogger("").getHandlers()){
+               Logger.getLogger("").removeHandler(h);
+           }
+
+           Handler consoleLogHandler = new ConsoleHandler();
+           consoleLogHandler.setFormatter(new Formatter() {
+
+               @Override
+               public String format(LogRecord record) {
+                   // if record.getMessage() is returned the TSV format gets trashed
+                   System.out.println(record.getMessage());
+                   return "";
+               }
+           });
+           Logger.getLogger("").addHandler(consoleLogHandler);
+
            for (String cmd : commandsToExecuteAndThenQuit) {
                successful = shell.executeCommand(cmd).isSuccess();
                if (!successful)
```

However this seems very hacky... Is there currently anyway to inject a custom formatter from my application? Is there a better solution for avoiding corrupting the TSV output?

Thanks!

**Comment by jvalkeal** [comment]
We're doing housekeeping in issues and closing ones which are potentially stale due to recent changes in a project. We are now more up to date with `Spring Boot` starting with release `2.1.0` and work in `3.x` making shell compatible with `Spring Framework 6` and `Spring Boot 3`.

If you think issue should not have been closed, try to re-open or open a new issue with updated info.
