### ISSUE TITLE
Could not find org.springframework.shell:spring-shell-management:3.0.0-SNAPSHOT.

### ISSUE THREAD

**Issue by vangie** [spring-projects/spring-shell#521]
```
         > Could not resolve org.springframework.shell:spring-shell-starter:3.0.0-SNAPSHOT.
            > Could not parse POM https://repo.spring.io/snapshot/org/springframework/shell/spring-shell-starter/3.0.0-SNAPSHOT/spring-shell-starter-3.0.0-20220906.184950-23.pom
               > Could not find org.springframework.shell:spring-shell-management:3.0.0-SNAPSHOT.
```

I could not find 'spring-shell-management' in https://repo.spring.io/ui/native/snapshot/org/springframework/shell

**Comment by zthreefires** [comment]
> Ups, that is build mistake and should not be in maven pom.

when I try to run Gradle build, Console still output:
> Could not find org.springframework.shell:spring-shell-management:3.0.0-SNAPSHOT.
     Required by:
         project : > org.springframework.shell:spring-shell-starter:3.0.0-SNAPSHOT:20220907.163755-26
         project : > org.springframework.shell:spring-shell-starter:3.0.0-SNAPSHOT:20220907.163755-26 > org.springframework.shell:spring-shell-autoconfigure:3.0.0-SNAPSHOT:20220907.163755-26
         project : > org.springframework.shell:spring-shell-starter:3.0.0-SNAPSHOT:20220907.163755-26 > org.springframework.shell:spring-shell-core:3.0.0-SNAPSHOT:20220907.163755-26
         project : > org.springframework.shell:spring-shell-starter:3.0.0-SNAPSHOT:20220907.163755-26 > org.springframework.shell:spring-shell-standard:3.0.0-SNAPSHOT:20220907.163755-26
         project : > org.springframework.shell:spring-shell-starter:3.0.0-SNAPSHOT:20220907.163755-26 > org.springframework.shell:spring-shell-standard-commands:3.0.0-SNAPSHOT:20220907.163755-26
         project : > org.springframework.shell:spring-shell-starter:3.0.0-SNAPSHOT:20220907.163755-26 > org.springframework.shell:spring-shell-table:3.0.0-SNAPSHOT:20220907.163755-26

**Comment by jvalkeal** [comment]
Yes, was just about to re-open as noticed same thing with gradle.

**Comment by jvalkeal** [comment]
Fixing broken metadata by removing those file. Maybe we bring it back when concept is more solid.
