### ISSUE TITLE
Ctrl+left, Ctrl+right not bound to backwards-word, forward-word

### ISSUE THREAD

**Issue by sirianni** [spring-projects/spring-shell#53]
ctrl-left yields: `1;5D`
ctrl-right yeilds: `1;5C`

These are bound in `/etc/inputrc` which works in all other readline-based applications.

```
# mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
```

Is spring-shell using JLine?  JLine supports inputrc.

**Comment by ericbottard** [comment]
Hi, Spring Shell currently uses JLine2.
I have successfully tested the above configuration (I'm on a Mac, copied your lines in `~/.inputrc` where JLine2 is looking for the file. Maybe this is what you need to do). 

See also https://github.com/jline/jline2/wiki/Configuration-Properties where you can change the default lookup location of the inputrc config file (if copy/pasting or symlinking is a no-go for you).

HTH

**Comment by sirianni** [comment]
Thanks Eric for following up.  Looks like the issue is that the latest release of Spring's `rest-shell` uses `jline-1.0.S2-B` which (apparently?) doesn't properly handle `inputrc`.  I tested using Spring Shell's `helloworld` app and `ctrl-left` and `ctrl-right` works as expected
