### ISSUE TITLE
Option Validation

### ISSUE THREAD

**Issue by oeztuce** [spring-projects/spring-shell#56]
It would be very helpful when spring-shell support Validation like JSR-311 for options.

E.g. an String option should have minimum length of 3 (search key word)
public void search(@Size(min = 3, message = "Search text must have minimum length of 3.")
                              @CliOption key = "text"
                              searchText)

**Comment by ericbottard** [comment]
This is a very interesting idea. Created https://jira.spring.io/browse/SHL-167 to track this, as JIRA is our preferred tool for this project.

Thanks for your contribution!
