### ISSUE TITLE
Feature request: ability to prefix all commands in a ShellComponent

### ISSUE THREAD

**Issue by klr8** [spring-projects/spring-shell#564]
It would be useful to have the ability to prefix all commands defined in a ShellComponent.
For instance:
```
@ShellComponent(prefix = "backend")
public class BackendCommands {

    @ShellMethod("Connect to the backend.")
    public void connect(String token) throws Exception {
        ...
    }
}
```
This would result in a "backend.connect" command.

A prefix ability would allow more consistency in command naming. For instance, you could also have "db.connect" and "kibana.connect" commands. Furthermore, using command line completion after typing the "backend" prefix would give you a nice overview of all backend related commands.

**Comment by jvalkeal** [comment]
I'm closing this in favour of #637. New annotation model is going to better designed and will allows to do these type of things more easily.
