### ISSUE TITLE
Handle whitespace in option value

### ISSUE THREAD

**Issue by Leo927** [spring-projects/spring-shell#567]
```myshellscript mycommand -option "a banana"``` 
And the option will have a value of "a instead of a banana. 
If the option has an arity of infinite, option will be two values ["\"a", "banana\"'] rather than a single value ["a banana"]

**Comment by jvalkeal** [comment]
Can you show how you defined a command. In sample https://github.com/spring-projects/spring-shell/blob/main/spring-shell-samples/src/main/java/org/springframework/shell/samples/e2e/OptionalValueCommands.java those work like this:

```
my-shell:>e2e anno optional-value --arg1 foo
Hello foo
my-shell:>e2e anno optional-value --arg1 "foo"
Hello foo
my-shell:>e2e anno optional-value --arg1 "foo bar"
Hello foo bar
my-shell:>e2e reg optional-value --arg1 foo
Hello foo
my-shell:>e2e reg optional-value --arg1 "foo"
Hello foo
my-shell:>e2e reg optional-value --arg1 "foo bar"
Hello foo bar
```

**Comment by Leo927** [comment]
Yes, it handles white space in interactive mode. But it doesn't in non-interactive mode.
