### ISSUE TITLE
sample app not working anymore

### ISSUE THREAD

**Issue by huxi** [spring-projects/spring-shell#6]
The helloworld example isn't working for me with a fresh build of revision 82adda6db9a5b5233088ba08033f9f72cb19a750, neither is my own.

It starts and simply shows an unconfigured shell, i.e. no Banner, no Prompt, no commands.

**Comment by ericbottard** [comment]
Hi, I've just tested this and all works fine for me. Built with both maven and gradle, as documented in the README.

Please feel free to re-open or comment if you're still experiencing issues.
