### ISSUE TITLE
Does spring-shell support unicode?

### ISSUE THREAD

**Issue by songlunzhao** [spring-projects/spring-shell#60]
For example I want to create a command to import a file with japanese file name , something like

```
import  --f "some japanese fiile name"
```

currently seems it does not work.
My code is like

``` java
@CliCommand(value = "import", help = "Import file")
  public String importFile(@CliOption(key = {"", "f", "file"}, mandatory = true, help = "file name") String fileName)
{
}
```

**Comment by ericbottard** [comment]
It should, will try to add tests asap to make sure it does.

Note that if you really want to have an arg that points to a File, you should make it of type java.io.File (that way, you'll get auto-completion, etc)

**Comment by songlunzhao** [comment]
Yes. I find that Spring Shell works fine on Linux (UTF-8). But it does not work on Windows Japanese version. Looks like Windows uses a different encoding :-(.

**Comment by ericbottard** [comment]
Are you at least able to input the name of the file in a plain shell window under windows?

Also, what does a simple java program that prints the value of the `file.encoding` system variable give you?

**Comment by songlunzhao** [comment]
Yes. I was able to input the file name in a plain shell window. The file.encoding variable gave me MS932.

**Comment by ericbottard** [comment]
In last resort, the Shell tokenizer supports `\uxxxx` escapes. Closing this
