### ISSUE TITLE
Question for Arity

### ISSUE THREAD

**Issue by eubnara** [spring-projects/spring-shell#611]
![image](https://user-images.githubusercontent.com/12639125/211801637-841f0dc7-7a5e-4818-a34b-26fd0aa29c67.png)
![image](https://user-images.githubusercontent.com/12639125/211801683-cf6a585a-a6a7-4c84-9f31-34a41124f579.png)

According to "current" document, it seems to take multiple values separated by **spaces** when specifying arity.
However, with version 2.1.4, it only takes multiple values if it is separated by **comma**.

Examples are gone on the 2.1.4 documentation. (https://docs.spring.io/spring-shell/docs/2.1.4/site/reference/htmlsingle/#using-shell-options-arity)

Is it expected behavior that it does not allow to get multiple values separated by **spaces**?
I guess this commit(https://github.com/spring-projects/spring-shell/commit/7042d1f83beee33aef42dc98ce96299a99af2ed3) impacts on this behavor.

![image](https://user-images.githubusercontent.com/12639125/211802590-91fc0e68-9240-45c7-87f8-64654a9e83e0.png)

**Comment by jvalkeal** [comment]
Thanks pointing this out! Now that I tried it myself it's indeed caused not-so-great handling of position parameters vs. parsing option type, vs. type conversions.

We really need to revisit this area so that it works properly.

**Comment by jvalkeal** [comment]
Issues #614 and #616 contains fixes and got backported to `2.1.x`. There's also changes in docs.

This is in samples:

https://github.com/spring-projects/spring-shell/blob/448c507ce967784120592aead52e43507a171a26/spring-shell-samples/src/main/java/org/springframework/shell/samples/e2e/ArityCommands.java#L92-L97

If you want to try then need to pick snapshots.

**Comment by jvalkeal** [comment]
Closing as I think it's handled with previous commits.
