### ISSUE TITLE
Better support command line no argument flags i.e. arity of 0 for CliOption

### ISSUE THREAD

**Issue by caliginouspierson** [spring-projects/spring-shell#65]
Should be able to have a command with options that don't allow parameters. I.e.
Something like

```
 @CliOption(key = { "debug" }, mandatory = false, help = "Start server in debug mode" ,  noParameter = "true") final String message
```

would allow
    server start -debug
but not
    server start -debug yes

**Comment by ericbottard** [comment]
There is already support for such parameters, not exactly in the way you describe though.
Have a look at `@CliOption` `specifiedDefaultValue` and `unspecifiedDefaultValue`, which allow the simulation of 0-arity options.

Note that Spring Shell is inherently built around the concept of 1-arity options, so this is likely the best you're gonna get.

**Comment by Vity01** [comment]
I also vote for this feature. It's a must have.

**Comment by ericbottard** [comment]
As stated above, this is already present, with the only "downside" (which I'm afraid is not gonna be "fixed" because it's in the DNA of Spring Shell) of letting the user **also** specify `--debug true` (or `false` for that matter) if she wants to.

But having just `server start --debug` is definitenly supported:

```java
@CliOption(key = { "debug" }, mandatory = false, help = "Start server in debug mode" ,  specifiedDefaultValue = "true") boolean debug
```

**Comment by Vity01** [comment]
Ahh sorry, I got it now. Thanks for the quick reply.
And how to define command like 
*mv /home/x /home*
without using --in and --out prefixes? 
Key value can be empty only for 1 Option.

**Comment by ericbottard** [comment]
> And how to define command like
mv /home/x /home
without using --in and --out prefixes?

You can't, again this is pretty much at the core of DNA of Spring Shell: options have to start with `--` (except for _at most_ one of them). Sorry :(
