### ISSUE TITLE
Converters are not called

### ISSUE THREAD

**Issue by ivangfr** [spring-projects/spring-shell#667]
Hi guys, I've recently upgrade this project [spring-webflux-reactive-databases](https://github.com/ivangfr/spring-webflux-reactive-databases) that uses **spring-shell** to **spring-boot** `2.7.8` and [**spring-shell** `2.1.6`](https://github.com/spring-projects/spring-shell/releases/tag/v2.1.6).

However, I've noticed that my converter [`CreateOrderProductConverter`](https://github.com/ivangfr/spring-webflux-reactive-databases/blob/master/client-shell/src/main/java/com/ivanfranchin/clientshell/converter/CreateOrderProductConverter.java) is not called.

The `CreateOrderProductConverter` is used [here](https://github.com/ivangfr/spring-webflux-reactive-databases/blob/master/client-shell/src/main/java/com/ivanfranchin/clientshell/command/OrderShellCommands.java#L50) to convert a `String` with format `"<product-1-id:quantity>[;<product-n-id:quantity>]"` to `Set<CreateOrderRequest.ProductDto>`

If I downgrade to **spring-shell** `2.1.5`, it works. Thanks!

**Comment by jvalkeal** [comment]
Thanks reporting this. Must be regression in fixes made for options handling.
