### ISSUE TITLE
Converse with user mode

### ISSUE THREAD

**Issue by rmohta** [spring-projects/spring-shell#69]
Most of the options in Spring Shell are around single command execution. If we could have a converse mode, that will be a good addition (my thoughts). 

I have made some changes on my local copy and it seems to work well with existing commands.

Let me know, if this is already present and I have missed it or if anyone is interested in this feature.

**Comment by ericbottard** [comment]
Is this the same as https://github.com/spring-projects/spring-shell/pull/67 ?

**Comment by rmohta** [comment]
Hi Eric,

  Yes. But I had taken a different approach. Build it as an extension, and
ask user to define to reflect in application context.

**Comment by ericbottard** [comment]
Closing as a duplicate. This will definitely not be implemented in Shell 1. Considering ways to allow users to do it in Shell 2

**Comment by MingningShao** [comment]
Well, it seems that the 2.x still did not have this function...
