### ISSUE TITLE
NPE thrown in Table.calculateColumnWidths() line 85 when only a header is defined

### ISSUE THREAD

**Issue by cverges-se** [spring-projects/spring-shell#70]
The following causes an NPE to be thrown:

``` java
Table table = new Table();

table.addHeader(0, new TableHeader("A"));
table.addHeader(1, new TableHeader("B"));

table.newRow().addValue(0, "C");
```

Expected result:

```
A  B
C
```

Actual result:

Null pointer exception thrown on line 85/86 of Table.calculateColumnWidths() due to use of `tableRow.getValue(headerEntryKey).length()` without checking whether `tableRow.getValue(headerEntryKey)` is valid first.

**Comment by ericbottard** [comment]
Closing old issue, as there is now a new Table library (package `org.springframework.shell.table`) that should be used instead
