### ISSUE TITLE
Feature request: Add mechanism to allow for partial console output during processing of intensive commands

### ISSUE THREAD

**Issue by cverges-se** [spring-projects/spring-shell#71]
Processing of some commands can take several seconds to minutes, depending on the business logic complexity.  Waiting to return a string can make it look like the shell has frozen while this processing is on-going.  Having a means to write messages to the console before returning a final String is useful to ease the user experience.

**Comment by cverges-se** [comment]
To clarify, System.out.println() works, but it doesn't allow for use of the associated utilities (like ANSI printing).  This request is to allow for linking into the JLineShell input/output framework.

**Comment by ericbottard** [comment]
Actually, you **can**. Could you clarify what you mean by
> linking into the JLineShell input/output framework.

**Comment by joelmarty** [comment]
@ericbottard you said we could do async output, but how would you do it?

**Comment by ericbottard** [comment]
I said you could do output (ie your commands can do whatever they please, in addition to returning a result [that would get printed]), and you could do async (ie your commands can spawn other threads that would work in the background). But I don't thing doing both is a good thing (similar to what happens in your regular shell when a background process continues to write to the console while you're still trying to type stuff).

This is good input for some feature request for v2 though, I'll keep that in mind.

**Comment by ericbottard** [comment]
Tidying old 1.x issues
