### ISSUE TITLE
3.0.2 flow component dose not work

### ISSUE THREAD

**Issue by TokgoRonin** [spring-projects/spring-shell#714]
Environment：JDK19, spring-boot 3.0.5, spring-shell 3.0.2

i use this demo:
![Screenshot_20230415-153647.jpg](https://user-images.githubusercontent.com/26754622/232196331-3c682e3c-1b38-4ac4-ab83-cf80cb72bbbc.jpg)

build project to a jar.
 then use cmd: java -jar spring-shell-learning.jar

it success open a shell, but when i type component string, it return: "Got value: null"

But when I use another version of：spring-boot 2.7.0, spring-shell 2.1.8

It can work as excepted return。

Not only StringInput, PathInput, PathSearch, Confirmation, SingleSelect, MutiSelect also not work.

**Comment by jvalkeal** [comment]
Can you show us a sample project we could run? Our sample https://github.com/spring-projects/spring-shell/blob/fa1adeaa82c7667eb62ca8caa94a934a499b332b/spring-shell-samples/src/main/java/org/springframework/shell/samples/standard/ComponentCommands.java#L51 works fine.

**Comment by TokgoRonin** [comment]
> I've had similar problem with the flow component, but the root cause seemed to be, that the terminal wasn't properly initialized (or may be the shell initialization was not complete due the exception thrown from the terminal initialization).
> 
> The issue with terminal initialization I've solved by adding **org.jline:jline-terminal-jna** dependency (was part of Spring Shell 2.x). After that is the flow component working.
> 
> Environment: Java 17, Windows (terminal: cmd), Spring Shell 3.0.2

Thanks, i will try it later!

**Comment by TokgoRonin** [comment]
> I've had similar problem with the flow component, but the root cause seemed to be, that the terminal wasn't properly initialized (or may be the shell initialization was not complete due the exception thrown from the terminal initialization).
> 
> The issue with terminal initialization I've solved by adding **org.jline:jline-terminal-jna** dependency (was part of Spring Shell 2.x). After that is the flow component working.
> 
> Environment: Java 17, Windows (terminal: cmd), Spring Shell 3.0.2

Thanks, it works!!

**Comment by jvalkeal** [comment]
Looks like this was resolved by other user.

**Comment by wimdeblauwe** [comment]
I have the same issue in my application using Spring Boot 3.0.6 and Spring Shell 3.0.2. Is the recommended way forward now that all users of Spring Shell will have to manually add that extra dependency? According to https://github.com/jline/jline3#jansi-vs-jna you need that dependency for things to work on Windows and for *nix systems, it will also work better. Maybe some better out-of-the-box defaults can be provided, or this should be clearly documented I think?

**Comment by wimdeblauwe** [comment]
For others that have this issue: If you are on Maven, add this dependency:

```
        <dependency>
            <groupId>org.jline</groupId>
            <artifactId>jline-terminal-jna</artifactId>
            <version>3.21.0</version>
        </dependency>
```

(Check the version of jline that Spring Shell is using. For 3.0.2, this is JLine 3.21.0)

**Comment by gurkanucar** [comment]
> I've had similar problem with the flow component, but the root cause seemed to be, that the terminal wasn't properly initialized (or may be the shell initialization was not complete due the exception thrown from the terminal initialization).
> 
> The issue with terminal initialization I've solved by adding **org.jline:jline-terminal-jna** dependency (was part of Spring Shell 2.x). After that is the flow component working.
> 
> Environment: Java 17, Windows (terminal: cmd), Spring Shell 3.0.2

Thank you, it works!
