### ISSUE TITLE
By default spring shell supports keyword args. Provide support for list+keyword args

### ISSUE THREAD

**Issue by prongs** [spring-projects/spring-shell#72]
```
@CliCommand(value = "do something", help = "do something")
  public String doSomething(
    @CliOption(key = {"option1"}, mandatory = true, help = "option1") String option1,
    @CliOption(key = {"option2"}, mandatory = true, help = "option2") String option2)

```

Allows me to run `do something --option1 value1 --option2 value2` on the cli. This is taking arguments as keyword arguments.

Now I want to be able to run `do something value1 value2` and have the same effect as the previous command. For this I have to do this:

```
@CliCommand(value = "do something", help = "do something")
  public String doSomething(
    @CliOption(key = {""}, mandatory = true, help = "pair") String pair) {
    split = pair.split("\s+");
    if(pair.length != 2) {
        throw Exception
    }
    option1 = pair[0];
    option2 = pair[1];
   ...
   ...
}
```

This was taking arguments as list arguments.

I want both, i.e. `do something --option1 value1 --option2 value2`  and `do something value1 value2` both should work and have the same effect. 

My current approach was to do this:

```
public abstract class BaseCommand implements ExecutionProcessor {
  @Override
  public ParseResult beforeInvocation(ParseResult parseResult) {
    Object[] args = parseResult.getArguments();
    if (args != null && Sets.newHashSet(args).size() == 1) {
      if (args[0] instanceof String) {
        String[] split = ((String) args[0]).split("\\s+");
        if (split.length == args.length) {
          parseResult = new ParseResult(parseResult.getMethod(), parseResult.getInstance(), split);
        }
      }
    }
    return parseResult;
  }
}
```

And have all my `Component` subclasses extend `BaseCommand`.

All I'm saying is, this should be supported out of the box, without having to hack around. 

As an extended functionality, I'd like to suggest a mixing of list and keyword args. I like python's way of doing this, which enforces that all list arguments have to be provided before all keyword arguments.

**Comment by ericbottard** [comment]
Could you elaborate, maybe with an example?

**Comment by prongs** [comment]
Updated the description

**Comment by ericbottard** [comment]
Thanks for taking the time to document what you meant.
This seems to be "positional parameters", which is a feature we were reluctant to add (see https://jira.spring.io/browse/SHL-97 and https://jira.spring.io/browse/SHL-38) but is starting to get some traction. This is likely to be introduced in Spring Shell v2 then

**Comment by prongs** [comment]
Cool. I'd like to be of help.

**Comment by adityakishore** [comment]
Lack of positional parameter is one of the biggest frustration for our user since the commands become too verbose.

**Comment by ericbottard** [comment]
Tidying old 1.x issues.
Won't be added to Shell 1. Available in Shell 2
