### ISSUE TITLE
simultaneous command execution on different instances on Bootstrap.getJLineShellComponent

### ISSUE THREAD

**Issue by praagarw** [spring-projects/spring-shell#73]
In a JVM say I create two instances aka instance1 and instance2 using new Bootstrap(). I expected that if a user send's multiple commands to instance1 then the commands must execute sequentially. However if a user sends commands to instance1 and then immediately to instance2, then both the commands should be able to run in parallel. Unfortunately this doesn't happen, i.e. the commands on instance1 and instance2 are executed sequentially. 

This behaviour is observed cause in SimpleExecutionStrategy.execute method synchronization is on SimpleExecutionStrategy.class. This should instead be synchronized on instance of  SimpleExecutionStrategy.

I'll be glad to provide a patch if the guru's agree with me, just send me an email.

Regards!

**Comment by ericbottard** [comment]
Tidying old 1.x issues.

Spring Shell was not designed to support creating several instances of some core classes, and this is not likely to be ever implemented, given we expect to interact with (one) user.
