### ISSUE TITLE
Question - Application level options for spring shell.

### ISSUE THREAD

**Issue by slorello89** [spring-projects/spring-shell#739]
👋  I have a question about options in Spring Shell. Apologies, I'm on the newer side to Spring in general so this might seem a bit dense. I'm writing a CLI tool that's meant to connect to Redis, and Ideally I'd like to be able to drive the application's configuration from startup think:

```
java -jar cli-tool.jar --hostname hostname --port port
```

From what I can tell if I run them in a way that would make spring boot happy:

```
java -jar cli-tool.jar --hostname=hostname --port=port
```

And pass it into `app.run` it does get autowired. There's a big caveat however, because immeditately after cleanly autowriring everything, the application immediately dies with:

```
No command found for '--host=hostname --port=6379'
org.springframework.shell.CommandNotFound: No command found for '--host=hostname --port=6379'
```

Because of course that's not a command name. However, if I don't pass the args into `app.run`, they aren't being autowired into the application and the services I'm trying to configure with them are just getting nulls to work with.

I can pass them directly into the commands I want to use them in, but then they again won't get autowired into the services I need.

I feel like I must be missing something blatantly obvious? The best way I can think of to handle this is to circumvent the DI system altogether and just initialize the service I need in the Shell Command, but this feels like it's not the Spring way. Am I missing something?

thanks!

**Comment by jvalkeal** [comment]
Closing this as a duplicate/favour of discussion thread at https://github.com/spring-projects/spring-shell/discussions/613.

**Comment by jvalkeal** [comment]
Note that there is an internal discussion if this is ever going to be possible.
