### ISSUE TITLE
Is Spring Shell dead?

### ISSUE THREAD

**Issue by 4F2E4A2E** [spring-projects/spring-shell#75]
Hell there!

Soo we are goingto start a new project and i wonder if spring shell is dead, since spring is promoting similar functionality along with spring boot. 

Remote shell on github seems not to have a heart beat anymore.

Thank you for this project, i am looking forward to your answer.

Cheers

**Comment by cverges-se** [comment]
http://stackoverflow.com/questions/23950674/what-is-difference-between-spring-shell-and-crash

I think they try to do slightly different things, though may be misunderstanding some aspects.

**Comment by ericbottard** [comment]
Indeed, those two projects address different usecases.
This project (Spring Shell) is not dead. It serves its purpose and receives minor bug fixes from time to time. Major new features are unlikely to be added to this code branch. Instead, when time permits, we are working on a rewrite from scratch which will bring Spring Shell on par with latest approaches in the Spring ecosystem (e.g. Spring Boot), while maintaining backwards compatibility to the best extent.

**Comment by 4F2E4A2E** [comment]
Thank you for the info, it's much appreciated.
