### ISSUE TITLE
How can the internal commands be removed or overwritten in Spring-Shell?

### ISSUE THREAD

**Issue by 4F2E4A2E** [spring-projects/spring-shell#76]
The "--disableInternalCommands" param is known, i want to disable/overwrite some of the commands that get auto-loaded from org.springframework.shell.commands package, and I can't quite figure out how to do that. Is it possible?

See: http://stackoverflow.com/questions/29948898/remove-commands-from-spring-shell

**Comment by ericbottard** [comment]
Tidying old 1.x issues.
Selective disabling of commands will be available in Shell 2

**Comment by 4F2E4A2E** [comment]
Great, that you guys are continuing this project. When will shell 2 be available?

**Comment by ericbottard** [comment]
Some SNAPSHOTs are already available (from the 2.x branch). Reference documentation to come, look at the `samples` module if you're interested.

No dates set yet for a milestone / release, but should be pretty soon.
