### ISSUE TITLE
Unexpected comma inserted at the end of the parsed message

### ISSUE THREAD

**Issue by DarkSined** [spring-projects/spring-shell#763]
HI,

I'm implementing a CLI using spring-shell 3.1.0 and spring boot 3.1.0.
During testing I have seen that parsing the message from vscode produces this result:

```java
@Command(group = "SAMPLE", command = "sample")
public class SampleCmd {

    @Command(description = "TEST COMMAND", command = "create")
    public void create(
            @Option(description = "Name of the cluster", required = true) String name,
            @Option(description = "Setup topology of API Management (Accepted values: CLOUD, LOCAL)", required = true) @Pattern(message = "Accepted values: CLOUD, LOCAL", regexp = "CLOUD|LOCAL") String envType,
            @Option(description = "API host", defaultValue = "my.host.com") String apiHost,
            @Option(description = "API port", defaultValue = "443") int apiPort,
            @Option(description = "API Base Path", defaultValue = "/v3") String apiBasePath,
            @Option(description = "Enable HTTPS", defaultValue = "true") boolean useSsl) {
        System.out.println("OK");
    }
```

TEST 1: **OK**
![image](https://github.com/spring-projects/spring-shell/assets/37557336/8fe39336-85ac-4b90-88e7-5eea8be0f430)

TEST 2: **OK**
![image](https://github.com/spring-projects/spring-shell/assets/37557336/63c286c0-ca25-449e-b891-35b8d6d016f4)

TEST 3: **KO** Because when parsing the parameters a "," is added to the value and the validator throws an exception
<img width="1201" alt="image" src="https://github.com/spring-projects/spring-shell/assets/37557336/9d132bf2-58bd-45b1-b2b2-31fc1c70435c">

TEST 4: **KO** Because when parsing the parameters a "," is added to the value and the validator throws an exception
<img width="1677" alt="image" src="https://github.com/spring-projects/spring-shell/assets/37557336/ae813401-a3df-41c5-a45c-6fe002da8fcf">

TEST 5: **KO** Because when parsing the parameters a ","
<img width="1684" alt="image" src="https://github.com/spring-projects/spring-shell/assets/37557336/70f95440-81ec-46ad-8c8d-9af1944e59c1">

TEST 6: **KO** Because when parsing the parameters a ","
![image](https://github.com/spring-projects/spring-shell/assets/37557336/f3320d0c-a953-41c1-bc6e-64dce8b76b88)

I have enabled all logging to capture events and message parsing: [application.log.zip](https://github.com/spring-projects/spring-shell/files/11646353/application.log.zip)

**Comment by jvalkeal** [comment]
Thanks for the report. I see a same and it's a bit strange. I'll add comments when I know more about a root cause.

**Comment by jvalkeal** [comment]
Bug is in `ExtendedDefaultParser` which were originally copied from `jline` and modified for some other needs in a spring-shell. If cursor position was at the end of a line an empty argument were added, which then caused option to get two arguments and as on default there's no arity settings, conversion then added that comma(Default spring conversion logic from collection to string).

This was a good catch!

**Comment by jvalkeal** [comment]
This bug doesn't cause issues in `3.0.x` or `2.1.x` as actual spring-shell parsing framework discards extra empty args. JLine parser used in interactive mode is different than command line parsing in spring-shell. Should still backport.

**Comment by jvalkeal** [comment]
Reopen as changes we made were not good and introduced a regression #772.

I went through what's going on with `ExtendedDefaultParser` in `spring-shell`. Back in days, many moons ago a changes were requested in a `JLine` which originated from `spring-shell`. In a `JLine` class is `DefaultParser` and looks like `ExtendedDefaultParser` were equivalent of `DefaultParser` after its changes. Then `DefaultParser` moved on and we ended up with not-so-great duplicate code.

When looking `DefaultParser` it seems to be normal getting empty args from its parsing and with changes in this issue we naively tried to avoid getting empty args from a parser. We need to revert changes in this issue and do fixes elsewhere to handle empty args(which caused this 'comma' issue).

**Comment by jvalkeal** [comment]
@DarkSined @daniel-b2c2 It'd be great if you could try snapshots. If all ok, I'd like to cut a release.

**Comment by DarkSined** [comment]
HI,

using spring-boot 3.1.1-snapshot and spring-shell 3.1.1-snapshot it seems to work:

Test 1: **OK**

![image](https://github.com/spring-projects/spring-shell/assets/37557336/b91a855c-296c-4ab5-8347-901d2113e8ed)

Test 2: **OK**

![image](https://github.com/spring-projects/spring-shell/assets/37557336/48bd3a2f-7d23-48b1-adac-bbae77111d45)

If I use the <TAB> I have no problems:

![image](https://github.com/spring-projects/spring-shell/assets/37557336/0a3b79bc-6af3-41e5-bef0-4792d2f932e2)

![image](https://github.com/spring-projects/spring-shell/assets/37557336/2102f710-4156-4efc-9f18-ac8ec737a936)

**Comment by jvalkeal** [comment]
Cool!

**Comment by daniel-b2c2** [comment]
Thanks for checking, I will also check now.

**Comment by daniel-b2c2** [comment]
looks good, thanks so much for a prompt fix. 💯
