### ISSUE TITLE
Add hooks for custom shutdown logic

### ISSUE THREAD

**Issue by cverges-se** [spring-projects/spring-shell#77]
I'd like to hook into Spring Shell's shutdown procedure, calling some custom handlers to clean up the system before exiting fully.  Registering with the JVM's shutdown notifier results in some race conditions where things that I may want to use might be half-shutdown at that time.  Utilizing Spring Shell's exit/Ctrl-C mechanisms would be more ideal.

**Comment by ericbottard** [comment]
Hi. What about using @PreDestroy beans?

**Comment by cverges-se** [comment]
Thanks for the suggestion.  Yes, @PreDestroy seems to work to address the clean-up problem.  It doesn't address the (not mentioned) use case of canceling an exit if the system is in an unrecoverable state, but I have no specific need for that feature at this time.
