### ISSUE TITLE
Duplicate characters on autocomplete, and no autocomplete for next --param

### ISSUE THREAD

**Issue by daniel-b2c2** [spring-projects/spring-shell#772]
Hi,

**Primary Bug**
In 3.1.1-SNAPSHOT, typing a command causes duplication of characters on autocomplete, it's difficult to describe in word so here it is as a set of actions:
I will partially type myCommand, tab to autocomplete it, tab again to get suggestions on params, and see the bug.

```
prompt>myCo
```

```
prompt>myCo<TAB>
```

```
prompt>myCo<TAB>
Group Name
myCommand
```

```
prompt>myCommand
```

```
prompt>myCommand<TAB>
```

```
prompt>mmyCommand 
```

see how there's two `m` in mmyCommand

The purpose of tab at the end, was to show `--option` options that might be appropriate.

**Associated Bug**
Secondary to this issue, should be noted that listing suggestions for the next set of parameters doesn't work either, you have to now type at least one `-` to allow the suggestions to appear.

**Another associated bug**
This issue extends to values of parameters too, so when autocompleting values for parameters e.g. `myCommand --version <TAB>` actual `myCommand --version `, was expecting the ValueProvider used to make value suggestions such as 0.1.3 but now does nothing unless you type at least 1 character. 

**Annoying functionality in previous 3.1.0**
Note that in 3.1.0 there was an annoying feature where ValueProviders would be mingled with commands even with the correct arrity, example:

A command which has a mandatory parameter with exactly one value for it.

Expected:
```
myCommand --version <TAB>
Notable Values Group
1.0
2.0
3.0
```

Actual
```
myCommand --version <TAB>
others
--help -h
Notable values group
1.0
2.0
3.0
```

Clearly others such as --help and -h are not possible autocompletion values, they are suggestions for the next parameter, but they should not have been suggested as exactly 1 value has not yet been entered

**Comment by jvalkeal** [comment]
I'm going to close this issue in favour of #763 which I reopened. I added some notes there.

**Comment by jvalkeal** [comment]
Thanks all comments, closing if favour of #763 which had new fixes.
