### ISSUE TITLE
Autocomplete tab causes error

### ISSUE THREAD

**Issue by DarkSined** [spring-projects/spring-shell#773]
HI,

i am using spring boot 3.1.0 with spring-shell 3.1.0 on vscode.
When I TAB on an option the command fails because a space is added:

![image](https://github.com/spring-projects/spring-shell/assets/37557336/8e00bfc1-b4f2-4278-aebf-b04705151df9)

If I don't TAB on the command option, the space is not added and the command works:

![image](https://github.com/spring-projects/spring-shell/assets/37557336/dc0fa37e-0d05-4dbd-8369-48c9140a4f9d)

**Comment by daniel-b2c2** [comment]
https://github.com/spring-projects/spring-shell/issues/766

**Comment by jvalkeal** [comment]
Thanks all comments, closing if favour of #763 which had new fixes.
