### ISSUE TITLE
Parse error on short options

### ISSUE THREAD

**Issue by proactif** [spring-projects/spring-shell#776]
Hi,

Using this code

```
    @ShellMethod
    public void test(
        @ShellOption(value = { "-a", "--aa" }, defaultValue = "a default") String a,
        @ShellOption(value = { "-b", "--bb" }, defaultValue = "b default") String b
    ) {
        log.info("a = {}", a);
        log.info("b = {}", b);
    }
```

Calling 

> test --aa ok --bb ok

gives me
> a = ok
> b = ok

as I expected.
But calling

> test -a ok -b ok

results in

> a = ok,-b,ok
> b = b default

Is this the expected behaviour of the command line parser ?
I really expected the short options to be equivalent to the long ones. 

Am I missing  something here ?
Is there a way to get this to work ?

**Comment by jvalkeal** [comment]
Which spring-shell version you're using?

**Comment by proactif** [comment]
I'm using version 3.1.0

**Comment by proactif** [comment]
Great, I will try 3.1.1 then.
3.1.0 was the last version I found on maven central, sorry.

**Comment by jvalkeal** [comment]
Yeah, you probably tried it before it was synced to central index.
