### ISSUE TITLE
CommandContext in shell method

### ISSUE THREAD

**Issue by max91** [spring-projects/spring-shell#779]
Hello, I can’t figure out how to get the `CommandСontext` in the method.

I am trying this:

```java
@ShellMethod
public String hi(
    CommandContext commandContext
) {
    return "hi";
}
```

But I don't think this is the right approach. Can you help me?

 Using this:
 
 ```xml
 <dependency>
    <groupId>org.springframework.shell</groupId>
    <artifactId>spring-shell-starter</artifactId>
    <version>2.1.10</version>
</dependency>
```

**Comment by jvalkeal** [comment]
Going to reopen this to make it as enhancement.

**Comment by jvalkeal** [comment]
Probably not going to touch old legacy `@ShellMethod` features but should be doable with `@Command` annotated methods.
