### ISSUE TITLE
Possible to execute several commands on one line ?

### ISSUE THREAD

**Issue by Xinerfapre** [spring-projects/spring-shell#780]
Hello,

Is it possible to execute several commands on one line? 

When I run : 
``` cmd
java -jar myshell.jar command1 args command2
```
"command1" is executed with argument "args" but command2 is not executed.

If I run : 
``` cmd
java -jar myshell.jar command1 --arg1 args command2
```
"command1" is executed with two arguments "args" and "command2".

**Comment by jvalkeal** [comment]
Currently it's not possible. Just out of interest why would you want to do this on a spring-shell level as usually things like this are done on a terminal level like in bash `command1 && command2`.

**Comment by Xinerfapre** [comment]
Sorry for the late reply.

I wish I could run multiple commands at the same time in the same shell instance.
Like, for example, in interactive mode, being able to configure and then run a treatment with the configuration of the previous command :
````cmd
my-interactive-shell > db "mybase" port 0000 url "0.0.0.0" connect
````
or
````cmd
my-interactive-shell > db "mybase" && port 0000 && url "0.0.0.0" && connect
````
And can also be used to run several commands in non-interactive mode.
For exemple in non-interactive mode :
````cmd
java -jar myshell.jar db "mybase" port 0000 url "0.0.0.0" initbase
````
or
````cmd
java -jar myshell.jar db "mybase" && port 0000 && url "0.0.0.0" && initbase
````

Other cases for exemple :
````cmd
my-interactive-shell > myecho "Hello" runthread
````
or
````cmd
my-interactive-shell > myecho "Hello" && runthread
````
or
````cmd
java -jar myshell.jar myecho "Hello" runthread
````
or
````cmd
java -jar myshell.jar myecho "Hello" && runthread
````

Is it possible?
