### ISSUE TITLE
Windows CMD and Powershell interactive mode does not display characters properly when I interact with the shell

### ISSUE THREAD

**Issue by yaharga** [spring-projects/spring-shell#781]
I'm basically copy/pasting `flow showcase1` and `flow showcase2` from [here](https://github.com/spring-projects/spring-shell/blob/main/spring-shell-samples/spring-shell-sample-commands/src/main/java/org/springframework/shell/samples/standard/ComponentFlowCommands.java) and the issue I'm having is that when the terminal appears, my Log4J2 logs overlap the prompt, and it does not appear properly.

For example, when single-selecting, as soon as I use the arrow keys, it jitters and I can't see what I'm selecting. Same goes for all other prompts (like multiselect). I keep getting:
```bash
  option1
? option2
  option3
```

I wish it was that clean, though, because it's like that, I can't see anything highlighted properly. I have to see above the last line to guess what's happening. The icons are not appearing properly even "[x]" just shows up as "🯄".

Also the ansi is disabled for the logs until spring-shell interactive mode is exited (colors show up when user is prompted). What's the issue?

**Comment by jvalkeal** [comment]
Are you using `jna` or `jansi` libs which are required on windows? i.e. via `spring-shell-starter-jna`.

**Comment by jvalkeal** [comment]
Indeed I see some characters on win not working(think we need to be more strict on default there). Other than that it looks ok.

![image](https://github.com/spring-projects/spring-shell/assets/50398/f15175cd-b5d0-40cc-800b-8af39a1d23f1)

Looks like you have other issues as well. Can you post a screenshots or recording to see what it actually looks like. Also more info about you win env might be helpful.

**Comment by yaharga** [comment]
All I did was throw the file from [here](https://github.com/spring-projects/spring-shell/blob/main/spring-shell-samples/spring-shell-sample-commands/src/main/java/org/springframework/shell/samples/standard/ComponentFlowCommands.java) into my project and keep the gradle file shown. I changed nothing else in my project. This is the updated relevant `build.gradle` file:

```groovy
dependencies {

  implementation ('net.minecrell:terminalconsoleappender:1.3.0') {
    exclude group: 'org.jline', module: 'jline-reader'
  }

  implementation 'org.jline:jline-reader:3.23.0'

  implementation 'org.springframework.boot:spring-boot-starter'
  implementation 'org.springframework.boot:spring-boot-starter-log4j2'
  implementation 'org.springframework.shell:spring-shell-starter-jna'

  modules{
    module('org.springframework.boot:spring-boot-starter-logging') {
      replacedBy('org.springframework.boot:spring-boot-starter-log4j2', 'Use Log4j2 instead of Logback')
    }
  }
}

deppendencyManagement {
  imports {
    mavenBom 'org.springframework.shell:spring-shell-dependencies:3.1.1'
  }
}
```

So, if I remove the `terminalconsoleappender`, it prints just like how you showed in your screenshot, but everything printed before the prompt shows up does not support ansi. Without Spring-Shell (before adding it to my project), log4j2 was printing colors all fine, but when I add Spring-Shell, ansi support is gone until the prompt appears, then when I exit and the program shuts down, the ansi support is back and the logs show colors.

When I add `terminalconsoleappender`, and change the `log4j2.xml` configuration to support the package:

```xml
<TerminalConsole>
    <PatternLayout pattern="%highlight{[%d{HH:mm:ss} %level]: %msg%n%xEx}" disableAnsi="${tca:disableAnsi}"/>
</TerminalConsole>
```

It prints with ansi support from the start, all is good, but then, it says it:
> unable to create a system terminal, creating a dumb terminal

When I am prompted, I type in "help", hit `enter`, then have to press a key (I press an arrow key, for example) for the help manual to show up. When I type `flow showcase1`, it does nothing, I press a key, then I get `shell:>` again, like I did nothing. When I type `exit`, it does nothing, I press any key, then it shows me the logs that exited. Even in debug mode I don't get much.

I get the following when I type `help` and press `enter`:
> Evaluate input with line=[help], command[help]
> Tokenizing arguments [help]

Then it goes on. It also prints the following:
> @{bold Built-In Commands}

I'm guessing there's still a root issue with ansi support somehow. I'm not sure what I'm doing. The same thing happens in PowerShell and in CMD. Is there something else that's obvious that I'm missing, or is Windows just not supported much?

**Comment by jvalkeal** [comment]
That implementation creates its own terminal and so does spring-shell so not sure if those can work together. If you create a sample project which I can build and run I can take a closer look. It's not a good idea to copy snippets from a comments as then you're never on a same sample code.

One other note is that jline `3.23.0` had some radical changes to std input/err which have caused issues to many people. I don't say that's related here but good to keep that mind. Thought that's easy to test by going back to `3.21.0`.
