### ISSUE TITLE
Aliases not working as expected with Annotations

### ISSUE THREAD

**Issue by iheffernan** [spring-projects/spring-shell#796]
When using Legacy Annotations, I am able to annotate a method as such:

`@ShellMethod(value = "Exit the shell.", key = {"logout","quit", "exit"})`

and the corresponding help message properly parses the multiple method aliases:

`logout, quit, exit: Exit the shell.`

However, when using the new `@Option` annotation, the help and parsing get garbled:

`@Command(description = "Exit the shell", alias = {"logout","quit", "exit"})`

`logout, logout quit exit: Exit the shell`

as you can see, all the aliases are crammed together into a single space-separated alias.

Am I misunderstanding the `alias` property? If so, what is the correct way to accomplish what is currently available in the Legacy Annotation? NOTE: I have also tried using an array of `command` values and I get a similar result:

`@Command(description = "Exit the shell", command = {"logout","quit", "exit"})`

yields

`logout quit exit: Exit the shell`

Using Spring Shell v3.1.1

**Comment by jvalkeal** [comment]
Thanks for pointing out misbehaviour with `@Command` and help page template.
