### ISSUE TITLE
Feature Request: Tab completion callback mechanism for arguments

### ISSUE THREAD

**Issue by cverges-se** [spring-projects/spring-shell#81]
When filling in command line arguments, it would be useful to have a callback mechanism that Spring Shell uses to activate custom handlers for completion of argument values.

Example:   ```export data --file <TAB>```

The ```<TAB>``` in this case could call a file match handler that then prints a list of potential file matches to the screen, or even returns a single match.  Use of a Collection<String> as the return from the handler might work well here, where if the Collection is only 1 element large, Spring Shell uses that element and moves to the next argument.

**Comment by ericbottard** [comment]
I'm not sure what you're referring to here. If by 
> When filling in command line arguments
you mean Spring Shell commands (annotated with `@CliCommand`), then there is already support for that (see below). If OTOH you're talking about "real" command line arguments (to the process), then there is no way Spring Shell can do something here.

So we'll assume you're talking `@CliCommand` arguments. There is support for that, with an extension mechanism even (see https://github.com/spring-projects/spring-shell/blob/master/src/main/java/org/springframework/shell/core/Converter.java). And as matter of fact, there is already support for what you describe: just have your argument be of type `java.io.File` (or `java.io.File[]` for [multiple](https://github.com/spring-projects/spring-shell/commit/4c18cfb8f4875dc7517f7cffdebf1c6da15c41cf))

**Comment by cverges-se** [comment]
Outstanding!  Yes, that's exactly what I was talking about.  I just missed it in the documentation, I guess.  Thanks for pointing it out.

**Comment by ericbottard** [comment]
Glad I could help :)
