### ISSUE TITLE
Make Result of last command available to all commands

### ISSUE THREAD

**Issue by prongs** [spring-projects/spring-shell#85]
Taking inspiration from python shell, where last command's output is stored in a special vairalbe `_` and can be used. 

I can see some use cases for such a functionality in sprint shell too. 

If there's not enough bandwidth, I can pick this up too, I'd need some pointers regarding where the changes are supposed to go.

**Comment by hoomanv** [comment]
Write your own ```ExecutionStrategy``` and have it returned by ```JLineShell.getExecutionStrategy()```.
You must be able to control executions, keep the results and use them in future executions all in your own custom ```ExecutionStrategy```

**Comment by prongs** [comment]
@hoomanv: Thanks for the suggestion. However, the solution you propose is an application level solution of the problem statement. I think such a feature could be good from the platform itself. Nevertheless, you have given me a starting point. I'll look into the code and try to add the feature. 

Thanks.

**Comment by ericbottard** [comment]
Tidying old 1.x issues.

Will not be implemented in core Spring Shell 1. May be considered as an Expander in Spring Shell 2
