### ISSUE TITLE
The description of the parameter cannot be displayed in help

### ISSUE THREAD

**Issue by ouyang7923** [spring-projects/spring-shell#885]
`
@ShellComponent("")  
@Slf4j  
public class Curl2FtpCommand {  
...  
@ShellMethod("sync method")  
public void sync(  @ShellOption(help = "source description") String source ...`  

text "source description"  It is never displayed in the help command results, how can i do?  

------------  
shell:>help  
AVAILABLE COMMANDS  
  
Built-In Commands  
       help: Display help about available commands  
       stacktrace: Display the full stacktrace of the last error.  
       clear: Clear the shell screen.  
       quit, exit: Exit the shell.  
       history: Display or save the history of previously run commands  
       version: Show version info  
       script: Read and execute commands from a file.  
  
Curl2Ftp Command  
       sync: sync method

**Comment by jvalkeal** [comment]
You'd see option level `help` (with legacy annotations) or `description` (with annotations/registration) with command help.

```
help sync
help --command sync
sync --help
```
