### ISSUE TITLE
StandardOut goes to StandardError in non-interactive mode

### ISSUE THREAD

**Issue by joanneshen** [spring-projects/spring-shell#891]
This issue seems to be more on the Linux side, Windows 10 system seemed to be fine. 

There is java process to kick off .bat file that kicks off Shell, then waits for the process to complete, then checks for standard input and error streams to determine if deployment process (the same applies for load/ingestion) was successful or failed.
 
Prior to Spring-shell 3.1.3 upgrade (and Spring-boot upgrade) standard out messages were available on getInputStream(). Everything that you see in Shell console (with exception of errors) were available in this stream. All errors, including NOTEs and warnings, were available in error stream (getErrorStream()).

After Spring-shell 3.1.3 upgrade, the input stream returns only the following:
“Welcome to XXXXXX ##.# command line client (c) XYZ Corporation
Type 'help' for a list of commands and options, type 'exit' to leave the shell.”
 
All the other message supposed to be standard out goes to standard error instead. 

We are also using build.gradle to do the build of the shell. It is in version 7.4 or 7.5.

**Comment by jvalkeal** [comment]
This was caused by changes in jline https://github.com/jline/jline3/issues/845. It's a bit complex issue there but with their next release we get some help to partially restore a functionality. In a meanwhile on linux you need to redirect stderr to stdout, i.e. `2>&1`.

**Comment by jvalkeal** [comment]
Looks like with #901 we're able to restore original behaviour(getting stuff written into stdout if there's a redirect) what comes for this stdout/stderr confusion.
