### ISSUE TITLE
Tab completion may fail with lazy initialization

### ISSUE THREAD

**Issue by icodening** [spring-projects/spring-shell#902]
tab-completion fails when `spring.main.lazy-initialization=true`, and will not found `ValueProvider`

## spring.main.lazy-initialization=true
<img width="1562" alt="image" src="https://github.com/spring-projects/spring-shell/assets/42876375/e6cf9f9e-7a8d-41e0-9df5-d20c36d1d52a">

## spring.main.lazy-initialization=false
<img width="1562" alt="image" src="https://github.com/spring-projects/spring-shell/assets/42876375/439f5b23-2268-4ced-a88f-44e10baffcfa">

**Comment by jvalkeal** [comment]
I'll see where the PR should be backported.

**Comment by jvalkeal** [comment]
There's some tech dept in old code which ultimately caused this. PR should be a good short term fix. I'll create new issues to change how this part of a completion should behave.
