### ISSUE TITLE
Spring Shell Test During Maven Test Block Application

### ISSUE THREAD

**Issue by denberr95** [spring-projects/spring-shell#926]
**HOW TO USE**

- VSCode
- Spring Boot 3.1.5
- Spring Shell 3.1.5

**WHAT I'M DOING**

I'm trying to implement unit tests using:

- Mockito
- jUnit5
- spring-shell-test
- spring-boot-starter-test
- spring-shell-test-autoconfigure

Depending on how I configured the shell contexts I get different behaviors

- Test execution test was blocked If I configure the following properties so:
  - spring.shell.interactive.enabled=true
  - spring.shell.noninteractive.enabled=true
  - spring.shell.context.close=false
- Test execution test was blocked If I configure the following properties so:
  - spring.shell.interactive.enabled=true
  - spring.shell.noninteractive.enabled=false
  - spring.shell.context.close=false
- Test execution test was blocked If I configure the following properties so:
  - spring.shell.interactive.enabled=false
  - spring.shell.noninteractive.enabled=true
  - spring.shell.context.close=false
- Test execution test was completed If I configure the following properties so:
  - spring.shell.interactive.enabled=false
  - spring.shell.noninteractive.enabled=false
  - spring.shell.context.close=false

It appears that you need to disable shell contexts to allow the @SpringBootShell annotation to complete.

**Comment by jvalkeal** [comment]
This is indeed a known issue as on default that interactive session hijacks test and never completes. One change we've been thinking is if we'd just leave noninteractive mode enabled and require user to enable others.

**Comment by denberr95** [comment]
It could be a good idea.
So based on the test scenario the user enables the type of shell session he needs.
I just have a doubt, if the CLI provided commands in both modes (interactive/non-interactive) would there be any effect?

**Comment by jvalkeal** [comment]
There should be no difference as that info is used at runtime.

**Comment by denberr95** [comment]
Ok great, in what milestone would it be possible to try it?

**Comment by jvalkeal** [comment]
Closing this as #1017 changed behaviour discussed above. It's in `3.3.x` snapshots and you can follow milestone scheduling.
