### ISSUE TITLE
Arity not working

### ISSUE THREAD

**Issue by Chris08tm** [spring-projects/spring-shell#930]
I have the method: 

```
 @Command(command = "create")
    public String create(
            @Option(
                    longNames = {"fp", "filePath"},
                    arity = OptionArity.EXACTLY_ONE,
                    required = true) String filePath){
        return "test";
    }
```
But after running the command 

shell:>c --fp
Not enough arguments for option 'fp', requires at least '0'

I have tried using arityMin = 1 and arityMax = 1, but regardless it always says " requires at least '0' " 
I am using 'springShellVersion' = "3.1.5"

**Comment by jvalkeal** [comment]
Are you sure you're using correct command as in your sample it's mapped to `create`.

Also using just `--fp`, as exactly one option argument is required, should result two errors, something like:
```
Not enough arguments for option 'fp', requires at least '0'
Missing mandatory option '--fp'
```

**Comment by Chris08tm** [comment]
Yes, sorry I shorted it to "c" after since I didn't want to continue to type "create" over and over, this is the annotation as it stands currently:
`@Command(command = "c")`
The error is correct, but my question is, shouldn't it return "requires at least '1'" rather than "requires at least '0'"

**Comment by jvalkeal** [comment]
doh, you're right, I was totally eyeing this wrongly. In this case parser internally reports `NOT_ENOUGH_OPTION_ARGUMENTS` but is passing wrong count to message template which is then reported back to user.
