### ISSUE TITLE
Unable to add alternative command

### ISSUE THREAD

**Issue by C-Otto** [spring-projects/spring-shell#941]
When I provide two `command` settings, I expect both to work. However, with the code shown below the `second` command cannot be used. Using `first` and pressing `<tab>` yields the second command (`first second`).

`@Command(description = "x", command = {"first", "second"})`

org.springframework.shell:spring-shell-starter:3.1.5

**Comment by jvalkeal** [comment]
Yes this would create command `first second`. There is an `alias` field in `@Command` you can use.

**Comment by C-Otto** [comment]
Thanks, I didn't know about the existence of `alias`.
