### ISSUE TITLE
Command alias not work on type level when sub command is empty

### ISSUE THREAD

**Issue by timnick-snow** [spring-projects/spring-shell#945]
```java
@Command(command = "foo", alias = "f")
public class MyCommand {
    @Command(command = "", alias = "")
//    @Command
    public String emptySub() {
        return "empty sub";
    }

    @Command(command = "bar", alias = "b")
    public String bar() {
        return "foo bar";
    }
}
```

```sh
shell:>foo bar
foo bar
shell:>f b
foo bar
shell:>foo 
empty sub
shell:>f
No command found for 'f'
shell:>
```

I can't use the `f` command

**Comment by jvalkeal** [comment]
Problem if we'd start to fully inherit `alias` from a class level is that then all the commands in a class would get same alias. It boils down to limitations in annotations that it's impossible to see if something is defined on a method level or if it comes from default annotation field.

I'd be fine changing current behaviour if we can come up with good sensible model how these annotations work together.
