### ISSUE TITLE
Collect the option parameters into a bean

### ISSUE THREAD

**Issue by timnick-snow** [spring-projects/spring-shell#955]
When there are a lot of option parameters, it is more convenient to use a bean to receive them.

For example, the following usage:

```java
    @Command(command = "foo")
    public void foo(@OptionBody FooOption fooOption) {
        //...
    }
    public static class FooOption{
        @Option(longNames = "verbose",shortNames = 'v')
        private boolean verbose;
        @Option(longNames = "other",shortNames = 'o')
        private String other;
    }
```

**Comment by jvalkeal** [comment]
Would be nice but it'd be good to see if framework implements similar ideas. https://github.com/spring-projects/spring-framework/issues/23618

**Comment by jvalkeal** [comment]
As similar type of request in framework were declined we're also declining this as don't want to come up with just a shell feature.
