### ISSUE TITLE
How can i block shell thread until my own thread pool executed

### ISSUE THREAD

**Issue by liutaohua** [spring-projects/spring-shell#98]
````
@Component
public class LoaderCommand implements CommandMarker {

    @CliCommand(value = "load file", help = "load local file data to target database")
    public String load(){
          // some code 
         Executors.newFixedThreadPool(1).execute(()->{
                      //do some thing
         });
    }
}
````

**Comment by snrmwg** [comment]
You can achieve that by using already available methods of `ExecutorService`. You can get a sophisticated solution by looking at the javadoc of the`ExecutorService` interface. More simply you can do something like this:

```
ExecutorService executorService = Executors.newFixedThreadPool(1);
executorService.execute / submit ....

executorService.shutdown();
executorService.awaitTermination(60, TimeUnit.SECONDS);
```

You need to call `shutdown()` before `awaitTermination(...)`. `awaitTermination` will block until all tasks have completed or the specified timeout occurs.

**Comment by ericbottard** [comment]
Thanks Marc for the example response. Closing as a non-Spring Shell issue
